#include <cplib/matrix/matrix_mod2.hpp>
#include <cplib/matrix/static_matrix_mod2.hpp>
#include <cplib/matrix/matrix.hpp>
#include <random>
using namespace cplib;
template<class A,class B> void multiplication(const A& a,const B& b){auto out=a*b;assert(out.h()==a.h()&&out.w()==b.w());for(Int i=0;i<a.h();++i)for(Int j=0;j<b.w();++j){bool want=false;for(Int k=0;k<a.w();++k)want^=a(i,k)&&b(k,j);assert(out(i,j)==want);}}
template<Int H,Int M,Int W> void fixed_product(){std::mt19937 rng(H*W+M);StaticMatrixMod2<H,M> a;StaticMatrixMod2<M,W> b;for(Int i=0;i<H;++i)for(Int j=0;j<M;++j)a(i,j)=int(rng()%2);for(Int i=0;i<M;++i)for(Int j=0;j<W;++j)b(i,j)=int(rng()%2);multiplication(a,b);}
template<Int N> void fixed_inverse(){std::mt19937 rng(N);StaticMatrixMod2<N,N> a;for(Int i=0;i<N;++i){a(i,i)=true;for(Int j=0;j<i;++j)a(i,j)=int(rng()%2);}assert(a.rank()==N&&a.determinant());auto inv=a.inverse();assert(inv&&a*(*inv)==(StaticMatrixMod2<N,N>::identity()));assert(a.pow(0)==(StaticMatrixMod2<N,N>::identity()));if constexpr(N>1){for(Int j=0;j<N;++j)a(1,j)=a(0,j);assert(!a.inverse()&&a.rank()==N-1);} }
int main(){std::mt19937 rng(69475);
 for(Int h:{0,1,39,40,65})for(Int w:{0,1,63,64,65,129})for(Int k:{0,1,63,65}){MatrixMod2 a(h,w),b(w,k);for(Int i=0;i<h;++i)for(Int j=0;j<w;++j)a(i,j)=int(rng()%2);for(Int i=0;i<w;++i)for(Int j=0;j<k;++j)b(i,j)=int(rng()%2);multiplication(a,b);assert(a.transposed().transposed()==a);}
 for(int trial=0;trial<300;++trial){Int h=rng()%70,w=rng()%75;MatrixMod2 a(h,w);Matrix<bool> scalar(h,w,false);for(Int i=0;i<h;++i)for(Int j=0;j<w;++j){bool v=rng()%2;a(i,j)=v;scalar(i,j)=v;}assert(a.rank()==scalar.rank());std::vector<bool> b(h);for(Int i=0;i<h;++i)b[i]=rng()%2;auto solved=a.solveLinearSystem(b),oracle=scalar.solveLinearSystem(b);assert(bool(solved)==bool(oracle));if(solved){assert(solved->particular==oracle->particular&&solved->basis==oracle->basis);}}
 for(Int n:{0,1,2,7,63,64,65,129}){MatrixMod2 a(n,n);for(Int i=0;i<n;++i){a(i,i)=true;for(Int j=0;j<i;++j)a(i,j)=int(rng()%2);}auto inverse=a.inverse();assert(inverse&&a*(*inverse)==MatrixMod2::identity(n));assert(a.determinant()&&a.pow(0)==MatrixMod2::identity(n));if(n>1){for(Int j=0;j<n;++j)a(1,j)=a(0,j);assert(!a.inverse());}}
 for(Int n=0;n<=8;++n)for(int trial=0;trial<30;++trial){MatrixMod2 a(n,n);Matrix<bool> scalar(n,n,false);for(Int i=0;i<n;++i)for(Int j=0;j<n;++j){bool v=rng()%2;a(i,j)=v;scalar(i,j)=v;}assert(a.determinant()==scalar.determinant());auto x=a.adjugate();auto y=scalar.adjugate();for(Int i=0;i<n;++i)for(Int j=0;j<n;++j)assert(x(i,j)==y(i,j));if(n%2==0){for(Int i=0;i<n;++i)for(Int j=0;j<i;++j){a(j,i)=a(i,j);scalar(j,i)=scalar(i,j);}assert(a.hafnian()==scalar.hafnian());}}
 fixed_product<0,0,0>();fixed_product<3,65,127>();fixed_product<40,64,67>();fixed_product<65,127,65>();fixed_product<40,64,0>();fixed_inverse<0>();fixed_inverse<1>();fixed_inverse<65>();
 StaticMatrixMod2<70,130> fixed;for(Int i=0;i<70;++i)for(Int j=0;j<130;++j)fixed(i,j)=int(rng()%2);for(Int h:{0,1,35,70})for(Int w:{0,1,63,64,65,128,130}){Matrix<bool> scalar(h,w,false);for(Int i=0;i<h;++i)for(Int j=0;j<w;++j)scalar(i,j)=fixed(i,j);std::vector<bool> b(h);for(Int i=0;i<h;++i)b[i]=rng()%2;auto x=fixed.solveLinearSystem(b,h,w),y=scalar.solveLinearSystem(b);assert(bool(x)==bool(y));if(x)assert(x->particular==y->particular&&x->basis==y->basis);}
 MatrixMod2 rows(2,130);rows.setRowBits(0,std::string(130,'1'));rows.setRowBits(0,"10a1");assert(rows.rowBits(0,5)=="10010"&&rows.rowBits(0).size()==130);rows(1,0)=-3;rows(1,1)=2;assert(rows(1,0)&&!rows(1,1));fixed.setRowBits(0,"101");assert(fixed.rowBits(0,4)=="1010");auto square=initStaticMatrixMod2(std::array{std::array<int,2>{1,1},std::array<int,2>{1,0}});auto adj=square.adjugate();assert((square*adj)==identityStaticMatrixMod2<2>());square(1,1)=1;assert(square.hafnian());
}
