#include <cplib/collections/private/simd_bitset.hpp>
#include <cplib/collections/bitset_binary_trie.hpp>
#include <cplib/collections/bitset.hpp>
#include <random>
using namespace cplib;
template<class B> void check(Int n){std::mt19937 rng(69430);auto create=[&](Int v){std::vector<bool> bits(n);for(Int i=0;i<n;++i)bits[i]=i<7&&((v>>(6-i))&1);return B(bits);};auto trie=initBitSetBinaryTrie(create(0));std::vector<Int> counts(128);for(Int q=0;q<1500;++q){Int x=n?rng()%128:0,c=rng()%4;if(rng()%3){trie.incl(create(x),c);counts[x]+=c;}else if(counts[x]>=c){trie.excl(create(x),c);counts[x]-=c;}else{Int old=trie.len();bool threw=false;try{trie.excl(create(x),c);}catch(const std::invalid_argument&){threw=true;}assert(threw&&trie.len()==old);}assert(trie.len()==std::accumulate(counts.begin(),counts.end(),Int(0)));assert(trie.count(create(x))==counts[x]&&trie.contains(create(x))==bool(counts[x]));Int mask=n?rng()%128:0;std::vector<Int> order;for(Int i=0;i<128;++i)for(Int j=0;j<counts[i^mask];++j)order.push_back(i^mask);if(trie.len()){Int k=rng()%trie.len();assert(trie.get_kth(k,create(mask))==create(order[k]));if(!mask)assert(trie[from_end(trie.len()-k)]==create(order[k]));}Int l=0,u=0;for(Int i=0;i<128;++i){if((i^mask)<x)l+=counts[i];if((i^mask)<=x)u+=counts[i];}assert(trie.lowerBound(create(x),create(mask))==l&&trie.upperBound(create(x),create(mask))==u);if(q%200==0){auto copy=trie;copy.incl(create(x));assert(trie.count(create(x))+1==copy.count(create(x)));}}
 for(Int x=0;x<128;++x)trie.excl(create(x),counts[x]);
 assert(trie.len()==0);trie.incl(create(0),std::numeric_limits<Int>::max());bool overflow=false;try{trie.incl(create(0));}catch(const std::overflow_error&){overflow=true;}assert(overflow);}
int main(){check<BitSet>(7);check<SimdBitSet<2>>(7);check<SimdBitSet<512>>(7);check<ScalarBitSet<7>>(7);check<SimdBitSet<2,7>>(7);check<SimdBitSet<512,7>>(7);check<BitSet>(0);check<SimdBitSet<512,0>>(0);check<SimdBitSet<512>>(1027);BitSetBinaryTrie<BitSet> uninitialized;assert(uninitialized.len()==0);bool caught=false;try{uninitialized.count(BitSet(3));}catch(const std::invalid_argument&){caught=true;}assert(caught);}
