#include <cplib/tree/link_cut_tree.hpp>
#include <cplib/tree/lazy_subtree_link_cut_tree.hpp>
#include <cplib/tree/static_top_tree_dp.hpp>
#include <cplib/tree/rerooting_static_top_tree_dp.hpp>
#include <random>
#include <queue>
using namespace cplib;
struct Forest {Int n;std::vector<std::vector<Int>> adj;explicit Forest(Int n):n(n),adj(n){}std::vector<Int> parent(Int root,Int avoid=-1){std::vector<Int> p(n,-2),q{root};p[root]=avoid;for(std::size_t i=0;i<q.size();++i)for(Int v:adj[q[i]])if(v!=p[q[i]]){p[v]=q[i];q.push_back(v);}return p;}std::vector<Int> component(Int u,Int avoid=-1){auto p=parent(u,avoid);std::vector<Int> out;for(Int v=0;v<n;++v)if(p[v]!=-2)out.push_back(v);return out;}std::vector<Int> path(Int u,Int v){auto p=parent(u);if(p[v]==-2)return {};std::vector<Int> out;while(v!=u){out.push_back(v);v=p[v];}out.push_back(u);std::reverse(out.begin(),out.end());return out;}void link(Int u,Int v){adj[u].push_back(v);adj[v].push_back(u);}void cut(Int u,Int v){std::erase(adj[u],v);std::erase(adj[v],u);}};
struct Sum {Int sum=0,count=0;bool operator==(const Sum&)const=default;};
struct Action {Int value;}; // 等値演算子のない作用も遅延伝播できることを検証する。
template<class F> void lazy(){std::mt19937 rng(31819);auto action=[](Int v){if constexpr(std::is_same_v<F,Int>)return v;else return F{v};};auto extract=[](F f){if constexpr(std::is_same_v<F,Int>)return f;else return f.value;};auto merge=[](Sum a,Sum b){return Sum{a.sum+b.sum,a.count+b.count};};auto inv=[](Sum a){return Sum{-a.sum,-a.count};};auto map=[&](F f,Sum a){return Sum{a.sum+extract(f)*a.count,a.count};};auto comp=[&](F a,F b){return action(extract(a)+extract(b));};auto fi=[&](F f){return action(-extract(f));};
 for(int trial=0;trial<30;++trial){Int n=1+rng()%55;Forest naive(n);std::vector<Sum> initial(n);std::vector<Int> values(n);for(Int v=0;v<n;++v)initial[v]={values[v]=Int(rng()%21)-10,1};auto tree=initLazySubtreeLinkCutTree(initial,merge,Sum{},map,comp,action(0),inv,fi);auto plain=initLinkCutTree(values,std::plus<Int>{},Int(0),std::negate<Int>{});
  auto total=[&](const auto& vertices){Int sum=0;for(auto v:vertices)sum+=values[v];return Sum{sum,Int(vertices.size())};};auto apply=[&](const auto& vertices,Int x){for(auto v:vertices){values[v]+=x;plain.update(v,values[v]);}};
  for(int step=0;step<2200;++step){Int u=rng()%n,v=rng()%n,type=rng()%10;auto path=naive.path(u,v);if(type==0&&path.empty()){tree.link(u,v);plain.link(u,v);naive.link(u,v);}else if(type==1&&!naive.adj[u].empty()){v=naive.adj[u][rng()%naive.adj[u].size()];tree.cut(u,v);plain.cut(u,v);naive.cut(u,v);assert(tree.findRoot(u)==u&&tree.findRoot(v)==v);}else if(type==2){Int x=Int(rng()%21)-10;values[u]=x;tree.update(u,{x,1});plain.update(u,x);}else if(type==3&&!path.empty()){Int x=Int(rng()%21)-10;tree.pathApply(u,v,action(x));apply(path,x);}else if(type==4){Int x=Int(rng()%21)-10;tree.componentApply(u,action(x));apply(naive.component(u),x);}else if(type==5&&!naive.adj[u].empty()){v=naive.adj[u][rng()%naive.adj[u].size()];Int x=Int(rng()%21)-10;tree.subtreeApply(u,v,action(x));apply(naive.component(u,v),x);}else if(type==6){tree.makeRoot(u);assert(tree.findRoot(u)==u);}assert(tree.connected(u,v)==!naive.path(u,v).empty());assert(tree.get(u)==(Sum{values[u],1}));assert(tree.componentProd(u)==total(naive.component(u)));assert(plain.componentProd(u)==total(naive.component(u)).sum);path=naive.path(u,v);if(!path.empty()){assert(tree.pathProd(u,v)==total(path));assert(plain.pathProd(u,v)==total(path).sum);}if(!naive.adj[u].empty()){v=naive.adj[u][0];assert(tree.subtreeProd(u,v)==total(naive.component(u,v)));assert(plain.subtreeProd(u,v)==total(naive.component(u,v)).sum);}}
  auto shared=tree;shared.update(0,{71,1});assert(tree.get(0).sum==71);tree[from_end(1)]=Sum{18,1};assert(tree.get(n-1).sum==18);
 }
}
void noncommutative(){std::mt19937 rng(761);for(int trial=0;trial<30;++trial){Int n=30;Forest f(n);std::vector<std::string> values(n);for(Int i=0;i<n;++i)values[i]=char('a'+i%26);auto tree=initLinkCutTree(values,[](const auto& a,const auto& b){return a+b;},std::string{});for(int step=0;step<2500;++step){Int u=rng()%n,v=rng()%n;auto path=f.path(u,v);if(path.empty()){tree.link(u,v);f.link(u,v);}else if(rng()%3==0&&!f.adj[u].empty()){v=f.adj[u][0];tree.cut(u,v);f.cut(u,v);}else{std::string expected;for(Int x:path)expected+=values[x];assert(tree.pathProd(u,v)==expected);}if(rng()%4==0){values[u]=char('a'+rng()%26);tree.update(u,values[u]);}}}}
struct Cluster {Int weight=0,du=0,dl=0,d=0;bool operator==(const Cluster&)const=default;};
Cluster compress(Cluster a,Cluster b){return {a.weight+b.weight,a.du+b.du+b.weight*a.d,b.dl+a.dl+a.weight*b.d,a.d+b.d};}
Cluster rake(Cluster a,Cluster b){return {a.weight+b.weight,a.du+b.du,a.dl+b.du+b.weight*a.d,a.d};}
Cluster atEnd(Cluster a,Cluster b){return {a.weight+b.weight,a.du+b.du+b.weight*a.d,a.dl+b.du,a.d};}
void top_tree(){std::mt19937 rng(97531);for(int trial=0;trial<100;++trial){Int n=1+rng()%100,root=rng()%n;auto g=initUnWeightedUnDirectedGraph(n);Forest f(n);for(Int v=1;v<n;++v){Int p=rng()%v;g.add_edge(p,v);f.link(p,v);}auto hld=initHld(g,root);auto topology=initStaticTopTree(hld);assert(topology->numVertices==n&&topology->nodes.size()==UInt(2*n-1));std::vector<Int> weights(n),distance(n);std::vector<Cluster> forward(n),backward(n);for(Int v=0;v<n;++v){weights[v]=rng()%11;distance[v]=v==root?0:rng()%8;forward[v]={weights[v],weights[v]*distance[v],0,distance[v]};backward[v]={weights[v],0,weights[v]*distance[v],distance[v]};}
 auto fixed=initStaticTopTreeDP(topology,forward,compress,rake);auto dp=initRerootingStaticTopTreeDP(topology,forward,backward,compress,rake,compress,rake,atEnd);
 for(int step=0;step<100;++step){Int v=rng()%n;weights[v]=rng()%15;distance[v]=v==root?0:rng()%12;forward[v]={weights[v],weights[v]*distance[v],0,distance[v]};backward[v]={weights[v],0,weights[v]*distance[v],distance[v]};fixed.set(v,forward[v]);dp.set(v,forward[v],backward[v]);assert(fixed.getAll()==dp.getAll());for(Int r=0;r<n;++r){Int expected=0;auto p=f.parent(r);std::vector<Int> dist(n,-1),q{r};dist[r]=0;for(std::size_t i=0;i<q.size();++i)for(Int child:f.adj[q[i]])if(child!=p[q[i]]){Int edge=hld.parentOf(child)==q[i]?child:q[i];dist[child]=dist[q[i]]+distance[edge];q.push_back(child);}for(Int x=0;x<n;++x)expected+=weights[x]*dist[x];assert(dp.prod(r).du==expected);if(r==root)assert(fixed.getAll().du==expected);}}
 }
 for(int shape=0;shape<3;++shape){Int n=100000;std::vector<Int> p(n,-1);for(Int v=1;v<n;++v)p[v]=shape==0?v-1:shape==1?0:(v-1)/2;auto tree=initStaticTopTreeFromParent(p);std::vector<Int> height(tree->nodes.size(),1);for(Int node=n;node<Int(height.size());++node)height[node]=1+std::max(height[tree->nodes[node].left],height[tree->nodes[node].right]);assert(height[tree->root]<100);auto dp=initStaticTopTreeDP(tree,std::vector<Int>(n,1),std::plus<Int>{},std::plus<Int>{});assert(dp.getAll()==n);dp.set(n-1,10);assert(dp.getAll()==n+9);}
}
int main(){lazy<Int>();lazy<Action>();noncommutative();top_tree();auto t=initLinkCutTree(Int(200000),std::plus<Int>{},Int(0),std::negate<Int>{});for(Int i=1;i<t.len();++i)t.link(i-1,i);t.update(0,1);t.update(t.len()-1,2);assert(t.pathProd(0,t.len()-1)==3);t.cut(99999,100000);assert(!t.connected(0,t.len()-1));}
