#include <cplib/math/factoradic.hpp>
#include <random>
#include <unordered_set>
using namespace cplib;
void check(const Factoradic& x,const BigInt& expected){assert(x.toBigInt()==expected);assert(x.str()==expected.str());auto d=x.digits();for(Int i=0;i<Int(d.size());++i)assert(d[i]>=0&&d[i]<=i);assert(d.empty()||d.back());assert(x.sgn()==expected.sgn());}
void pair(const BigInt& x,const BigInt& y){Factoradic a(x),b(y);check(a,x);check(b,y);check(a+b,x+y);check(a-b,x-y);check(a*b,x*y);assert(cmp(a,b)==cmp(x,y));if(y!=0){check(a/b,x/y);check(mod(a,b),mod(x,y));check(a%b,x%y);check(floor_div(a,b),floor_div(x,y));auto division=divmod(a,b);check(division.quotient,divmod(x,y).quotient);check(division.remainder,divmod(x,y).remainder);}}
int main(){std::mt19937_64 rng(31961);for(Int x:{std::numeric_limits<Int>::min(),Int(-1),Int(0),Int(1),std::numeric_limits<Int>::max()}){Factoradic a(x);assert(a.toInt()==x);check(a,BigInt(x));}Factoradic umax(std::numeric_limits<UInt>::max());assert(umax.toInt<UInt>()==std::numeric_limits<UInt>::max());for(int x=-128;x<=127;++x)assert(Factoradic(x).toInt<std::int8_t>()==x);for(int x=0;x<=255;++x)assert(Factoradic(x).toInt<std::uint8_t>()==x);
 for(int trial=0;trial<1600;++trial){Int x=std::bit_cast<Int>(rng()),y=std::bit_cast<Int>(rng());pair(BigInt(x),BigInt(y));Factoradic a(x);check(a*y,BigInt(x)*BigInt(y));if(y){check(a/y,BigInt(x)/BigInt(y));assert(BigInt(a%y)==BigInt(x)%BigInt(y));assert(BigInt(mod(a,y))==mod(BigInt(x),BigInt(y)));auto r=divmod(a,y);check(r.quotient,divmod(BigInt(x),BigInt(y)).quotient);assert(BigInt(r.remainder)==divmod(BigInt(x),BigInt(y)).remainder);}}
 for(Int n:{21,32,33,34,64,65,127,256,1000,5000}){std::vector<Int> digits(n+1);for(Int i=1;i<=n;++i)digits[i]=rng()%(i+1);for(bool negative:{false,true}){Factoradic x(digits,negative);BigInt ref=0;for(Int i=n;i>=1;--i)ref=ref*BigInt(i+1)+BigInt(digits[i]);if(negative)ref=-ref;check(x,ref);assert(Factoradic(ref)==x);for(Int y:{std::numeric_limits<Int>::min(),Int(-97),Int(-1),Int(1),Int(17),std::numeric_limits<Int>::max()}){check(x*y,ref*BigInt(y));check(x/y,ref/BigInt(y));assert(BigInt(x%y)==ref%BigInt(y));assert(BigInt(mod(x,y))==mod(ref,BigInt(y)));}for(Int k:std::vector<Int>{0,1,2,10,21,32,n,n+1}){auto fact=factorialFactoradic(k).toBigInt();check(x.modFactorial(k),ref%fact);}}}
 for(int trial=0;trial<80;++trial){Int n=22+rng()%180,m=22+rng()%180;std::vector<Int> da(n),db(m);for(Int i=1;i<n;++i)da[i]=rng()%(i+1);for(Int i=1;i<m;++i)db[i]=rng()%(i+1);Factoradic a(da,rng()%2),b(db,rng()%2);pair(a.toBigInt(),b.toBigInt());}
 for(Int n=0;n<=9;++n){std::vector<Int> p(n);std::iota(p.begin(),p.end(),0);Int rank=0;do{auto r=permutationRank(p);assert(r==rank);assert(r.toPermutation(n)==p);++rank;}while(std::next_permutation(p.begin(),p.end()));assert(factorialFactoradic(n)==rank);}
 for(Int n:{10,100,1000,100000}){std::vector<Int> p(n);std::iota(p.begin(),p.end(),0);std::shuffle(p.begin(),p.end(),rng);auto rank=permutationRank(p);assert(rank.toPermutation(n)==p);std::reverse(p.begin(),p.end());assert(permutationRank(p).toPermutation(n)==p);}
 auto big=factorialFactoradic(1000);for(auto a:{big,-big})for(auto b:{big,-big,big+1,-big-1,big-1,-big+1})pair(a.toBigInt(),b.toBigInt());for(Int k:{-1,0,1,2,123}){check(BigInt(k).sgn()<0?-Factoradic(k):Factoradic(k),BigInt(k).abs());}
 bool thrown=false;try{(void)(Factoradic(7)/0);}catch(const std::domain_error&){thrown=true;}assert(thrown);std::unordered_set<Factoradic> set;set.insert(big);assert(set.contains(factorialFactoradic(1000)));Factoradic x(100);x+=3;x-=2;x*=7;x/=2;assert(x==353);mod_assign(x,Int(-11));assert(x==1);x=353;x%=Int(-11);assert(x==-10);
}
