#include <cplib/graph/maxflow.hpp>
#include <cplib/graph/push_relabel.hpp>
#include <cplib/graph/lowerbound_maxflow.hpp>
#include <cplib/graph/hopcroft_karp.hpp>
#include <cplib/utils/project_selection.hpp>
#include <cplib/utils/k_project_selection.hpp>
#include <cplib/graph/dag_minimum_path_cover.hpp>
#include <cplib/graph/mincostflow.hpp>
#include <random>
#include <functional>
using namespace cplib;
void selection_test();
void mincost_test();
int main(){
    selection_test();
    mincost_test();
    std::mt19937 rng(24);
    for(int q=0;q<1500;++q){Int n=2+rng()%8;auto d=initMaxFlow(n);auto p=initPushRelabel(n);Int m=rng()%60;for(Int i=0;i<m;++i){Int a=rng()%n,b=rng()%n,c=rng()%30;assert(d.add_edge(a,b,c)==i&&p.add_edge(a,b,c)==i);}auto edges=d.get_edges();Int want=std::numeric_limits<Int>::max();for(Int mask=1;mask<(Int(1)<<n);mask+=2)if(!(mask&(Int(1)<<(n-1)))){Int sum=0;for(auto e:edges)if((mask&(Int(1)<<e.src))&&!(mask&(Int(1)<<e.dst)))sum+=e.cap;want=std::min(want,sum);}Int limit=rng()%100;Int a=d.flow(0,n-1,limit),b=p.flow(0,n-1,limit);assert(a==std::min(limit,want)&&a==b);assert(d.flow(0,n-1)==want-a&&p.flow(0,n-1)==want-b);assert(d.flow(0,n-1)==0&&p.flow(0,n-1)==0);
        auto check=[&](const auto& g){auto cut=g.min_cut(0);assert(!cut[n-1]);Int cap=0;std::vector<Int> balance(n);auto result=g.get_edges();assert(result.size()==edges.size());for(Int i=0;i<m;++i){auto e=result[i];assert(e.src==edges[i].src&&e.dst==edges[i].dst&&e.cap==edges[i].cap);assert(0<=e.flow&&e.flow<=e.cap);balance[e.src]-=e.flow;balance[e.dst]+=e.flow;if(cut[e.src]&&!cut[e.dst])cap+=e.cap;}assert(cap==want&&balance[0]==-want&&balance[n-1]==want);for(Int v=1;v<n-1;++v)assert(balance[v]==0);};check(d);check(p);
    }
    for(int trial=0;trial<1000;++trial){Int n=2+rng()%4,m=rng()%7;auto g=initLowerBoundMaxFlow(n);std::vector<std::tuple<Int,Int,Int,Int>> edges;for(Int i=0;i<m;++i){Int a=rng()%n,b=rng()%n,u=rng()%4,l=rng()%(u+1);g.add_edge(a,b,l,u);edges.emplace_back(a,b,l,u);}Int want=-1;std::vector<Int> bal(n);auto dfs=[&](auto&& self,Int i)->void{if(i==m){for(Int v=1;v<n-1;++v)if(bal[v])return;if(bal[0]+bal[n-1]==0&&bal[n-1]>=0)want=std::max(want,bal[n-1]);return;}auto [a,b,l,u]=edges[i];for(Int x=l;x<=u;++x){bal[a]-=x;bal[b]+=x;self(self,i+1);bal[a]+=x;bal[b]-=x;}};dfs(dfs,0);assert(g.flow(0,n-1)==want&&g.flow(0,n-1)==want);if(want>=0){for(auto e:g.get_edges()){assert(e.lower<=e.flow&&e.flow<=e.upper);bal[e.src]-=e.flow;bal[e.dst]+=e.flow;}assert(bal[0]==-want&&bal[n-1]==want);for(Int v=1;v<n-1;++v)assert(bal[v]==0);}}
    for(int trial=0;trial<500;++trial){Int l=rng()%40,r=rng()%40;auto a=initHopcroftKarp(l,r),b=initHopcroftKarp(l,r);auto flow=initMaxFlow(l+r+2);Int source=l+r,sink=source+1;for(Int i=0;i<l;++i)flow.add_edge(source,i,1);for(Int i=0;i<r;++i)flow.add_edge(l+i,sink,1);Int want=0;std::vector<std::vector<bool>> exists(l,std::vector<bool>(r));for(int phase=0;phase<5;++phase){for(int k=0;l&&r&&k<50;++k){Int u=rng()%l,v=rng()%r;a.add_edge(u,v);b.add_edge(u,v);flow.add_edge(u,l+v,1);exists[u][v]=true;}want+=flow.flow(source,sink);assert(a.matching()==want&&b.matching(false)==want&&a.matching()==want);std::vector<bool> usedL(l),usedR(r);for(auto [u,v]:a.get_matching()){assert(exists[u][v]&&!usedL[u]&&!usedR[v]);usedL[u]=usedR[v]=true;}assert(Int(a.get_matching().size())==want);}}
    {Int n=50000;auto d=initMaxFlow(n);auto p=initPushRelabel(n);for(Int i=1;i<n;++i){d.add_edge(i-1,i,7);p.add_edge(i-1,i,7);}assert(d.flow(0,n-1)==7&&p.flow(0,n-1)==7);}
    {auto p=initPushRelabel<UInt>(3);p.add_edge(0,1,std::numeric_limits<UInt>::max());p.add_edge(1,2,std::numeric_limits<UInt>::max());assert(p.flow(0,2)==std::numeric_limits<UInt>::max());assert(p.get_edges().size()==2);}
}
void selection_test(){
    std::mt19937 rng(25);
    for(int trial=0;trial<700;++trial){Int n=1+rng()%7;auto opt=initProjectSelection(n);std::vector<std::function<Int(Int)>> costs;std::vector<std::function<bool(Int)>> valid;for(int q=0;q<20;++q){Int i=rng()%n,j=rng()%n,w=rng()%10;bool value=rng()%2;switch(rng()%7){case 0:{Int a=Int(rng()%20)-10,b=Int(rng()%20)-10;opt.add_unary_cost(i,a,b);costs.push_back([=](Int mask){return (mask>>i&1)?b:a;});break;}case 1:{Int a=Int(rng()%20)-10,b=Int(rng()%20)-10,c=Int(rng()%20)-10,d=b+c-a-w;opt.add_pair_cost(i,j,a,b,c,d);costs.push_back([=](Int mask){bool x=mask>>i&1,y=mask>>j&1;return x?(y?d:c):(y?b:a);});break;}case 2:{std::vector<Int> ids(rng()%6);for(auto& id:ids)id=rng()%n;opt.add_gain_if_all(ids,value,w);costs.push_back([=](Int mask){for(Int id:ids)if(bool(mask>>id&1)!=value)return Int(0);return -w;});break;}case 3:opt.force(i,value);valid.push_back([=](Int mask){return bool(mask>>i&1)==value;});break;case 4:opt.imply(i,j);valid.push_back([=](Int mask){return !(mask>>i&1)||(mask>>j&1);});break;case 5:opt.add_cost_if_different(i,j,w);costs.push_back([=](Int mask){return ((mask>>i&1)!=(mask>>j&1))?w:0;});break;case 6:opt.add_gain(i,value,w);costs.push_back([=](Int mask){return bool(mask>>i&1)==value?-w:0;});break;}}
        Int want=std::numeric_limits<Int>::max();auto eval=[&](Int mask){Int value=0;for(auto& f:costs)value+=f(mask);return value;};for(Int mask=0;mask<(Int(1)<<n);++mask){bool good=true;for(auto& f:valid)good&=f(mask);if(good)want=std::min(want,eval(mask));}auto answer=opt.solve();assert(answer.feasible==(want!=std::numeric_limits<Int>::max()));if(answer.feasible){assert(answer.min_cost==want);Int mask=0;for(Int i=0;i<n;++i)if(answer.assignment[i])mask|=Int(1)<<i;assert(eval(mask)==want);for(auto& f:valid)assert(f(mask));assert(opt.solve().min_cost==want);}
    }
    for(int trial=0;trial<300;++trial){std::vector<Int> sizes={Int(1+rng()%4),Int(1+rng()%4),Int(1+rng()%4)};auto opt=initKProjectSelection(sizes);std::vector<std::vector<Int>> unary(3);std::vector<std::vector<Int>> pair(sizes[0],std::vector<Int>(sizes[1]));for(Int i=0;i<3;++i){unary[i].resize(sizes[i]);for(auto& x:unary[i])x=Int(rng()%20)-10;opt.add_unary_cost(i,unary[i]);}for(Int a=0;a<sizes[0];++a)for(Int b=0;b<sizes[1];++b)pair[a][b]=(a-b)*(a-b);opt.add_pair_cost(0,1,pair);Int lo=rng()%(sizes[0]+1),hi=Int(rng()%(sizes[1]+1))-1;opt.set_min(0,lo);opt.set_max(1,hi);Int t0=rng()%(sizes[0]+1),t2=rng()%(sizes[2]+1);opt.imply(0,t0,2,t2);std::vector<std::pair<Int,Int>> ge={{0,t0},{2,t2}},le={{1,hi}};opt.add_gain_if_all_ge(ge,5);opt.add_gain_if_all_le(le,3);opt.add_cost_if_ge_lt(0,t0,2,t2,7);
        auto evaluate=[&](const std::vector<Int>& v){Int cost=unary[0][v[0]]+unary[1][v[1]]+unary[2][v[2]]+pair[v[0]][v[1]];if(v[0]>=t0&&v[2]>=t2)cost-=5;if(v[1]<=hi)cost-=3;if(v[0]>=t0&&v[2]<t2)cost+=7;return cost;};Int want=std::numeric_limits<Int>::max();for(Int a=0;a<sizes[0];++a)for(Int b=0;b<sizes[1];++b)for(Int c=0;c<sizes[2];++c)if(a>=lo&&b<=hi&&(!(a>=t0)||c>=t2))want=std::min(want,evaluate({a,b,c}));auto answer=opt.solve();assert(answer.feasible==(want!=std::numeric_limits<Int>::max()));if(answer.feasible){assert(answer.min_cost==want&&evaluate(answer.assignment)==want);assert(answer.assignment[0]>=lo&&answer.assignment[1]<=hi);}
    }
    {auto p=initProjectSelection(1);p.force(0,true);p.force(0,false);assert(!p.solve().feasible);bool caught=false;try{p.add_gain(0,true,std::numeric_limits<Int>::min());}catch(const std::overflow_error&){caught=true;}assert(caught);}
    {auto p=initProjectSelection(2);bool caught=false;try{p.add_pair_cost(0,1,Int(1),Int(0),Int(0),Int(1));}catch(const std::invalid_argument&){caught=true;}assert(caught);}
    {auto g=initUnWeightedDirectedGraph(6);g.add_edge(0,1);g.add_edge(1,2);g.add_edge(3,4);assert(dag_minimum_path_cover(g)==3);}
}

void mincost_test(){
    std::mt19937 rng(26);
    for(int trial=0;trial<1000;++trial){Int n=2+rng()%4,m=rng()%8;auto g=initMinCostFlow(n);std::vector<Int> potential(n);for(auto& x:potential)x=Int(rng()%11)-5;for(Int i=0;i<m;++i){Int a=rng()%n,b=rng()%n,c=rng()%3,w=Int(rng()%5)+potential[b]-potential[a];g.add_edge(a,b,c,w);}auto edges=g.get_edges();std::vector<Int> balance(n),best(20,std::numeric_limits<Int>::max());auto enumerate=[&](auto&& self,Int i,Int cost)->void{if(i==m){for(Int v=1;v<n-1;++v)if(balance[v])return;if(balance[0]+balance[n-1]==0&&balance[n-1]>=0)best[balance[n-1]]=std::min(best[balance[n-1]],cost);return;}auto e=edges[i];for(Int f=0;f<=e.cap;++f){balance[e.src]-=f;balance[e.dst]+=f;self(self,i+1,cost+f*e.cost);balance[e.src]+=f;balance[e.dst]-=f;}};enumerate(enumerate,0,0);
        auto limited=g;Int limit=rng()%12;auto path=g.slope(0,n-1);assert((path.front()==std::pair<Int,Int>{0,0}));Int maxf=0;for(Int i=0;i<Int(best.size());++i)if(best[i]!=std::numeric_limits<Int>::max())maxf=i;assert(path.back().first==maxf&&path.back().second==best[maxf]);Int prev=std::numeric_limits<Int>::min();for(std::size_t i=1;i<path.size();++i){auto [f,c]=path[i];auto [pf,pc]=path[i-1];assert(f>pf&&(c-pc)%(f-pf)==0);Int slope=(c-pc)/(f-pf);assert(slope>prev);prev=slope;for(Int k=pf;k<=f;++k)assert(best[k]==pc+(k-pf)*slope);}auto [f,c]=limited.flow(0,n-1,limit);assert(f==std::min(limit,maxf)&&c==best[f]);auto [f2,c2]=limited.flow(0,n-1);assert(f+f2==maxf&&c+c2==best[maxf]);Int edgeCost=0;for(auto e:g.get_edges()){assert(0<=e.flow&&e.flow<=e.cap);balance[e.src]-=e.flow;balance[e.dst]+=e.flow;edgeCost+=e.flow*e.cost;}assert(edgeCost==best[maxf]&&balance[0]==-maxf&&balance[n-1]==maxf);for(Int v=1;v<n-1;++v)assert(balance[v]==0);
    }
    {auto g=initMinCostFlow(3);g.add_edge(0,1,1,0);g.add_edge(1,1,1,-1);bool caught=false;try{g.flow(0,2);}catch(const std::invalid_argument&){caught=true;}assert(caught);assert(g.slope(0,2,0).size()==1);}
    {auto g=initMinCostFlow<unsigned,int>(4);g.add_edge(2,2,1,-1);g.add_edge(0,1,3,-4);assert((g.flow(0,1)==std::pair<unsigned,int>{3,-12}));}
}
