#include <cplib/utils/itertools.hpp>
#include <set>
#include <random>
using namespace cplib;
template<class G> auto collect(G&& range){using T=std::remove_cvref_t<decltype(*range.begin())>;std::vector<T> out;for(const auto& x:range)out.push_back(x);return out;}
Int ipow(Int a,Int b){Int out=1;while(b--)out*=a;return out;}
int main(){
 auto p=collect(permutations(std::vector<Int>{2,1,1}));assert(p.size()==6&&p[0]==std::vector<Int>({2,1,1}));auto d=collect(distinct_permutations(std::vector<Int>{2,1,1}));assert(d==std::vector<std::vector<Int>>({{1,1,2},{1,2,1},{2,1,1}}));assert(collect(permutations(std::vector<Int>{})).size()==1);
 auto prod=collect(product(std::vector<Int>{0,1},3));assert(prod==std::vector<std::vector<Int>>({{0,0,0},{1,0,0},{0,1,0},{1,1,0},{0,0,1},{1,0,1},{0,1,1},{1,1,1}}));assert(collect(product(std::vector<Int>{},0)).size()==1&&collect(product(std::vector<Int>{},2)).empty());
 auto op=[](const std::string& a,const std::string& b){return "("+a+","+b+")";};std::vector<std::string> strings{"a","b","c"};assert(accumulated(strings,op)==std::vector<std::string>({"a","(a,b)","((a,b),c)"}));assert(accumulatedr(strings,op)==std::vector<std::string>({"(a,(b,c))","(b,c)","c"}));assert(accumulated(strings,op,std::string("x")).back()=="(((x,a),b),c)");assert(accumulatedr(strings,op,std::string("x"))[0]=="(a,(b,(c,x)))");assert(accumulated(std::vector<Int>{},std::plus<Int>{}).empty());
 for(Int n=0;n<=9;++n){std::vector<Int> v(n);std::iota(v.begin(),v.end(),1);for(Int r=-1;r<=n+1;++r){auto comb=collect(combinations(v,r));std::vector<std::vector<Int>> expected;for(UInt mask=0;mask<(UInt(1)<<n);++mask)if(std::popcount(mask)==r){std::vector<Int> x;for(Int i=0;i<n;++i)if((mask>>i)&1)x.push_back(v[i]);expected.push_back(x);}std::sort(expected.begin(),expected.end());assert(comb==expected);if(r>=0){auto sums=collect(combinations_withf(v,r,std::plus<Int>{}));if(r==0)assert(sums.empty());else {assert(sums.size()==comb.size());for(std::size_t i=0;i<sums.size();++i)assert(sums[i]==std::accumulate(comb[i].begin(),comb[i].end(),Int(0)));}}}auto fixed=collect(combinations<3>(v));auto dyn=collect(combinations(v,3));assert(fixed.size()==dyn.size());for(std::size_t i=0;i<fixed.size();++i)assert(std::vector<Int>(fixed[i].begin(),fixed[i].end())==dyn[i]);assert(collect(combinations<0>(v)).size()==1);}
 std::vector<std::string> words{"a","b","c","d","e"};auto folded=collect(combinations_withf(words,3,op));auto chosen=collect(combinations(words,3));for(std::size_t i=0;i<chosen.size();++i)assert(folded[i]==op(op(chosen[i][0],chosen[i][1]),chosen[i][2]));
 Int partition_counts[]={1,1,2,3,5,7,11,15,22,30,42};for(Int n=0;n<=10;++n){auto all=collect(partitions(n));assert(Int(all.size())==partition_counts[n]);assert(std::is_sorted(all.begin(),all.end()));for(auto x:all)assert(std::is_sorted(x.begin(),x.end())&&std::accumulate(x.begin(),x.end(),Int(0))==n);}
 std::mt19937 rng(8721);for(int trial=0;trial<250;++trial){Int n=rng()%6;std::vector<Int> upper(n);std::vector<std::pair<Int,Int>> bounds(n);std::vector<std::vector<Int>> choices(n);for(Int i=0;i<n;++i){upper[i]=rng()%4;Int l=Int(rng()%7)-3,r=l+upper[i]+1;bounds[i]={l,r};for(Int j=l;j<r;++j)choices[i].push_back(j);}auto b=collect(bounded_sequences(upper)),c=collect(cartesian_product(choices));assert(b.size()==c.size());for(std::size_t i=0;i<b.size();++i)for(Int j=0;j<n;++j)assert(b[i][j]+bounds[j].first==c[i][j]);for(Int sum=-9;sum<=9;++sum){std::vector<std::vector<Int>> expected;for(auto x:c)if(std::accumulate(x.begin(),x.end(),Int(0))==sum)expected.push_back(x);assert(collect(bounded_sum_sequences(sum,bounds))==expected);}}
 assert(collect(bounded_sum_sequences(3,0,2,2)).empty());assert(collect(cartesian_product(std::vector<std::vector<Int>>{{1},{}})).empty());
 for(Int n=0;n<=5;++n)for(Int l=-2;l<=1;++l)for(Int r=l;r<=3;++r){std::vector<std::vector<Int>> choices(n);for(auto& row:choices)for(Int x=l;x<r;++x)row.push_back(x);auto all=collect(cartesian_product(choices));std::vector<std::vector<Int>> weak,strict;for(auto x:all)if(std::is_sorted(x.begin(),x.end())){weak.push_back(x);if(std::adjacent_find(x.begin(),x.end())==x.end())strict.push_back(x);}assert(collect(nondecreasing_sequences(n,l,r))==weak);assert(collect(strictly_increasing_sequences(n,l,r))==strict);for(Int sum=-5;sum<=5;++sum){std::vector<std::vector<Int>> w,s;for(auto x:weak)if(std::accumulate(x.begin(),x.end(),Int(0))==sum)w.push_back(x);for(auto x:strict)if(std::accumulate(x.begin(),x.end(),Int(0))==sum)s.push_back(x);assert(collect(nondecreasing_sequences(n,sum,l,r))==w);assert(collect(strictly_increasing_sequences(n,sum,l,r))==s);}}
 Int bell[]={1,1,2,5,15,52,203,877};for(Int n=0;n<=7;++n){auto ids=collect(set_partitions_id(n));auto groups=collect(set_partitions(n));assert(Int(ids.size())==bell[n]&&ids.size()==groups.size());for(std::size_t i=0;i<ids.size();++i){std::vector<Int> rebuilt(n);for(Int j=0;j<Int(groups[i].size());++j)for(auto x:groups[i][j])rebuilt[x]=j;assert(rebuilt==ids[i]);}for(Int k=0;k<=n+1;++k){auto a=collect(set_partitions_id(n,k));auto b=collect(set_partitions(n,k));std::size_t count=0;for(const auto& x:groups)count+=Int(x.size())==k;assert(a.size()==count&&b.size()==count);}}
 for(Int n=0;n<=10;++n){Int expected=1;if(n%2)expected=0;else for(Int k=1;k<n;k+=2)expected*=k;auto all=collect(pairings(n));assert(Int(all.size())==expected);std::set<std::vector<std::pair<Int,Int>>> unique(all.begin(),all.end());assert(unique.size()==all.size());for(auto pairs:all){std::vector<Int> seen(n);for(auto [u,v]:pairs){assert(u<v);++seen[u];++seen[v];}for(auto c:seen)assert(c==1);}}
 for(Int n=0;n<=9;++n){auto all=collect(contiguous_partitions(n));assert(Int(all.size())==(n?Int(1)<<(n-1):1));for(Int k=0;k<=n+1;++k){auto fixed=collect(contiguous_partitions(n,k));std::vector<std::vector<Int>> expected;for(auto x:all)if(Int(x.size())==k+1)expected.push_back(x);assert(fixed==expected);}}
 Int catalan[]={1,1,2,5,14,42,132,429,1430};for(Int n=0;n<=8;++n){auto all=collect(parenthesis_sequences(n));assert(Int(all.size())==catalan[n]);assert(std::is_sorted(all.begin(),all.end()));for(auto s:all){Int balance=0;for(char c:s){balance+=c=='('?1:-1;assert(balance>=0);}assert(balance==0);}}
 for(Int n=1;n<=5;++n){std::set<std::vector<std::pair<Int,Int>>> unique;for(const auto& g:labeled_trees(n)){assert(g.len==n&&g.edge_count()==n-1);std::vector<std::pair<Int,Int>> e;for(auto x:g.edge_info)e.emplace_back(std::min(x.src,x.dst),std::max(x.src,x.dst));std::sort(e.begin(),e.end());unique.insert(e);}assert(Int(unique.size())==(n==1?1:ipow(n,n-2)));}
 for(Int n=0;n<=5;++n){Int count=0;for(const auto& g:simple_graphs(n)){assert(g.len==n);++count;}assert(count==(Int(1)<<(n*(n-1)/2)));assert(collect(simple_graphs(n,n*(n-1)/2+1)).empty());}
 for(int trial=0;trial<250;++trial){Int n=rng()%7;std::vector<std::vector<Int>> adj(n);auto g=initUnWeightedDirectedGraph(n);for(Int u=0;u<n;++u)for(Int v=0;v<n;++v)if(rng()%7==0){adj[u].push_back(v);g.add_edge(u,v);}std::vector<Int> vertices(n);std::iota(vertices.begin(),vertices.end(),0);std::vector<std::vector<Int>> expected;for(auto p:permutations(vertices)){std::vector<Int> pos(n);for(Int i=0;i<n;++i)pos[p[i]]=i;bool good=true;for(Int u=0;u<n;++u)for(Int v:adj[u])good&=pos[u]<pos[v];if(good)expected.push_back(p);}assert(collect(topological_orders(adj))==expected);assert(collect(topological_orders(g))==expected);}
 for(Int n=0;n<=4;++n)for(Int s=-1;s<=4;++s){auto all=collect(integer_vectors_l1(n,s));std::vector<std::vector<Int>> expected;for(auto x:cartesian_product(std::vector<std::vector<Int>>(n,{-4,-3,-2,-1,0,1,2,3,4}))){Int sum=0;for(auto v:x)sum+=std::abs(v);if(sum<=s)expected.push_back(x);}assert(all==expected);}
 auto cases=product(std::vector<Int>{0,1,2},3);auto sum=[](const auto& v){return std::accumulate(v.begin(),v.end(),Int(0));};auto bad=[&](const auto& v){return sum(v)+(v[0]==2);};auto failure=find_counterexample(cases,bad,sum);assert(failure&&failure->input==std::vector<Int>({2,0,0})&&failure->actual==3&&failure->expected==2);auto factory=[](){return integer_vectors_l1(2,2);};auto same=find_counterexample(factory,sum,sum);assert(!same);auto shrunk=shrink_counterexample(std::vector<Int>{12,-10,29},[](const auto& v){return std::find_if(v.begin(),v.end(),[](Int x){return x>=7;})!=v.end();});assert(shrunk==std::vector<Int>({7}));
 auto huge=product(std::vector<Int>{0,1},100000);auto it=huge.begin();assert((*it).size()==100000); // 全件生成をしないことと、途中終了を確認する。
}
