#include <cplib/collections/persistent_segtree.hpp>
#include <random>
using namespace cplib;
struct Sum{Int sum=0,n=0;bool operator==(const Sum&)const=default;};
struct Affine{Int a=1,b=0;};
int main(){std::mt19937_64 rng(177);auto op=[](Sum a,Sum b){return Sum{a.sum+b.sum,a.n+b.n};};auto map=[](Affine f,Sum x){return Sum{f.a*x.sum+f.b*x.n,x.n};};auto comp=[](Affine f,Affine g){return Affine{f.a*g.a,f.a*g.b+f.b};};
 for(Int n:{0,1,2,17,64}){std::vector<Sum> initial(n,Sum{1,1});auto t=initPersistentLazySegmentTree(initial,op,Sum{},map,comp,Affine{});std::vector<decltype(t)> versions{t};std::vector<std::vector<Int>> refs{std::vector<Int>(n,1)};for(int q=0;q<700;++q){Int a=rng()%versions.size(),b=rng()%versions.size(),l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);auto ref=refs[a];auto next=versions[a];switch(rng()%4){case 0:{Affine f{Int(rng()%2),Int(rng()%5)};next=next.apply(l,r,f);for(Int i=l;i<r;++i)ref[i]=f.a*ref[i]+f.b;break;}case 1:next=next.copy_range(versions[b],l,r);for(Int i=l;i<r;++i)ref[i]=refs[b][i];break;case 2:if(n){Int i=rng()%n,x=rng()%10;next=next.update(i,Sum{x,1});ref[i]=x;}break;case 3:{std::vector<Sum> values(n,Sum{7,1});auto independent=initPersistentLazySegmentTree(values,op,Sum{},map,comp,Affine{});next=next.copy_range(independent,l,r);for(Int i=l;i<r;++i)ref[i]=7;}}
 versions.push_back(next);refs.push_back(ref);a=rng()%versions.size();Int sum=std::accumulate(refs[a].begin()+l,refs[a].begin()+r,Int(0));assert(versions[a].get(l,r)==(Sum{sum,r-l}));Int limit=rng()%30,rr=l,sm=0;while(rr<n&&sm+refs[a][rr]<=limit)sm+=refs[a][rr++];assert(versions[a].max_right(l,[&](Sum x){return x.sum<=limit;})==rr);Int ll=r;sm=0;while(ll>0&&sm+refs[a][ll-1]<=limit)sm+=refs[a][--ll];assert(versions[a].min_left(r,[&](Sum x){return x.sum<=limit;})==ll);}}
 auto opstr=[](std::string a,std::string b){return a+b;};auto a=initPersistentSegmentTree(std::vector<std::string>{"a","b","c"},opstr,std::string{});auto b=a.update(1,"X");auto c=a.copy_range(b,1,3);assert(a.get_all()=="abc"&&c.get_all()=="aXc");assert(c[from_end(1)]=="c");c.set(0,"Z");assert(c.get_all()=="ZXc");assert(a.max_right(0,[](auto x){return x.size()<=2;})==2);assert(a.min_left(3,[](auto x){return x.size()<=2;})==1);
}
