#include <cplib/graph/general_weighted_matching.hpp>
#include <cplib/graph/general_weighted_matching_sparse.hpp>
#include <cplib/graph/dominator_tree.hpp>
#include <cplib/graph/dijkstra_radix.hpp>
#include <cplib/geometry/euclidean_mst.hpp>
#include <cplib/utils/mo.hpp>
#include <random>
#include <set>
using namespace cplib;
int main(){std::mt19937_64 rng(3901);
 for(Int n=0;n<=12;++n)for(int trial=0;trial<120;++trial){WeightedUnDirectedGraph<Int> g(n);std::vector<std::vector<Int>> w(n,std::vector<Int>(n));for(Int u=0;u<n;++u)for(Int v=u;v<n;++v)if(rng()%3){for(int k=0;k<2;++k){Int x=Int(rng()%31)-5;g.add_edge(u,v,x);if(u!=v)w[u][v]=w[v][u]=std::max(w[u][v],x);}}std::vector<Int> dp(1<<n);for(Int mask=1;mask<(1<<n);++mask){Int u=std::countr_zero(UInt(mask)),rest=mask^(1<<u);dp[mask]=dp[rest];for(Int v=u+1;v<n;++v)if(rest&(1<<v))dp[mask]=std::max(dp[mask],w[u][v]+dp[rest^(1<<v)]);}for(auto ans:{maximum_weight_matching(g),maximum_weight_matching_sparse(g)}){assert(ans.weight==dp.back());std::set<Int> used;Int sum=0;for(auto [u,v]:ans.matching){assert(used.insert(u).second&&used.insert(v).second);sum+=w[u][v];}assert(sum==ans.weight);}}
 for(Int n=1;n<=30;++n)for(int trial=0;trial<30;++trial){WeightedDirectedGraph<Int> g(n);std::vector<std::vector<Int>> adj(n);for(Int u=0;u<n;++u)for(Int v=0;v<n;++v)if(rng()%6==0){g.add_edge(u,v,rng()%100);adj[u].push_back(v);}Int root=rng()%n;auto idom=dominator_tree(g,root);assert(idom==dominator_tree(adj,root));auto reach=[&](Int banned){std::vector<bool> seen(n);std::vector<Int> q;if(root!=banned){seen[root]=true;q.push_back(root);}for(std::size_t i=0;i<q.size();++i)for(Int v:adj[q[i]])if(v!=banned&&!seen[v]){seen[v]=true;q.push_back(v);}return seen;};auto all=reach(-1);std::vector<std::vector<bool>> dom(n,std::vector<bool>(n));for(Int d=0;d<n;++d){auto without=reach(d);for(Int v=0;v<n;++v)dom[v][d]=all[v]&&!without[v];}for(Int v=0;v<n;++v){if(!all[v])assert(idom[v]==-1);else if(v==root)assert(idom[v]==root);else{assert(idom[v]!=v&&dom[v][idom[v]]);for(Int d=0;d<n;++d)if(d!=v&&d!=idom[v]&&dom[v][d])assert(dom[idom[v]][d]);}}assert(dijkstra_radix(g,root)==dijkstra(g,root));std::vector<Int> starts{root,Int(rng()%n),root};assert(dijkstra_radix(g,starts)==dijkstra(g,starts));auto path=shortest_path_dijkstra_radix(g,root,n-1);assert(path.cost==dijkstra(g,root)[n-1]);}
 for(Int n=0;n<60;++n)for(int trial=0;trial<15;++trial){std::vector<Point<Int>> p(n);for(auto& x:p)x={Int(rng()%31)-15,Int(rng()%31)-15};auto ans=euclidean_mst(p);assert(Int(ans.size())==std::max<Int>(0,n-1));auto dist=[&](Int u,Int v){Int dx=p[u].x-p[v].x,dy=p[u].y-p[v].y;return dx*dx+dy*dy;};Int sum=0;UnionFind uf(n);for(auto [u,v]:ans){assert(!uf.issame(u,v));uf.unite(u,v);sum+=dist(u,v);}std::vector<std::tuple<Int,Int,Int>> e;for(Int u=0;u<n;++u)for(Int v=0;v<u;++v)e.emplace_back(dist(u,v),u,v);std::sort(e.begin(),e.end());UnionFind ref(n);Int expected=0;for(auto [w,u,v]:e)if(!ref.issame(u,v)){expected+=w;ref.unite(u,v);}assert(sum==expected);}
 for(Int n=1;n<50;++n){UnWeightedUnDirectedGraph g(n);for(Int v=1;v<n;++v)g.add_edge(v,rng()%v);Int root=rng()%n;TreeMo mo(g,100,root);std::vector<Int> expected;for(Int q=0;q<100;++q){Int u=rng()%n,v=rng()%n;mo.insert(u,v);auto d=dijkstra(g,u);expected.push_back(d[v]+1);}Int size=1;std::set<Int> vertices{root};mo.run([&](Int u,Int v){assert(vertices.contains(u)&&!vertices.contains(v));vertices.insert(v);++size;},[&](Int u,Int v){assert(vertices.contains(u)&&vertices.contains(v));vertices.erase(v);--size;},[&](Int q){assert(size==expected[q]);});assert(vertices==std::set<Int>{root});}
 {WeightedDirectedGraph<UInt> g(4);UInt big=std::numeric_limits<UInt>::max()-10;g.add_edge(0,1,big);g.add_edge(1,2,5);g.add_edge(2,3,20);auto d=dijkstra_radix(g,Int(0));assert(d[1]==big&&d[2]==big+5&&d[3]==std::numeric_limits<UInt>::max());}
 {WeightedDirectedGraph<std::uint8_t> g(3);g.add_edge(0,1,200);g.add_edge(1,2,60);auto d=dijkstra_radix(g,Int(0));assert(d[1]==200&&d[2]==255);}
 {WeightedUnDirectedStaticGraph<Int> g(5);g.add_edge(0,1,7);g.add_edge(1,2,9);g.add_edge(2,0,8);g.add_edge(2,3,6);g.add_edge(3,4,5);g.build();assert(maximum_weight_matching(g).weight==14&&maximum_weight_matching_sparse(g).weight==14);}
 {UnWeightedDirectedGraph g(100000);for(Int i=1;i<g.len;++i)g.add_edge(i-1,i);auto d=dominator_tree(g,0);assert(d[0]==0);for(Int i=1;i<g.len;++i)assert(d[i]==i-1);}
 {std::vector<Point<Int>> p{{-1000000000,-1000000000},{1000000000,-1000000000},{1000000000,1000000000},{-1000000000,1000000000},{0,0}};assert(euclidean_mst(p).size()==4);}

}
