#include <cplib/collections/radix_heap.hpp>
#include <cplib/collections/max_heapqueue.hpp>
#include <cplib/collections/intset.hpp>
#include <cplib/collections/range_sort_array.hpp>
#include <cplib/collections/range_sort_segtree.hpp>
#include <cplib/collections/compressed_retroactive_priority_queue.hpp>
#include <cplib/collections/dynamic_retroactive_priority_queue_monoid.hpp>
#include <cplib/collections/indexed_retroactive_priority_queue.hpp>
#include <random>
#include <set>
using namespace cplib;
template<class Queue> void checkQueue(const Queue& q,SortOrder order){auto timeline=q.debugTimeline();std::set<Int> popped;Int pushSum=0,popSum=0;std::vector<std::pair<Int,Int>> remaining;for(auto& e:timeline){if(e.kind==qdkPush)pushSum+=*e.value;if(e.popped){popped.insert(e.popped->time);popSum+=e.popped->value;}}for(auto& e:timeline)if(e.kind==qdkPush&&!popped.contains(e.time))remaining.emplace_back(*e.value,e.time);Int sum=0;for(auto [v,t]:remaining)sum+=v;assert(q.len()==Int(remaining.size()));assert(q.sum()==sum&&q.poppedSum()==popSum&&sum+popSum==pushSum);if(remaining.empty())assert(!q.peek());else{std::sort(remaining.begin(),remaining.end());assert(q.peek()==(order==Ascending?remaining.front().first:remaining.back().first));}for(auto& e:timeline)assert(q.isRemaining(e.time)==(e.kind==qdkPush&&!popped.contains(e.time)));}
int main(){std::mt19937_64 rng(914);
 for(auto order:{Ascending,Descending}){RetroactivePriorityQueue<Int> fixed(31,order);DynamicRetroactivePriorityQueue<Int,Int> dynamic(order);std::vector<Int> times(31);std::iota(times.begin(),times.end(),0);CompressedRetroactivePriorityQueue<Int,Int> compressed(times,order);auto monoid=initDynamicRetroactivePriorityQueueMonoid<Int,Int,std::string>([](auto a,auto b){return a+b;},std::string{},[](Int x){return std::to_string(x)+",";},order);for(int q=0;q<4000;++q){Int t=rng()%31,value=Int(rng()%21)-10,kind=rng()%3;auto mutate=[&](auto& queue){if(kind==0)queue.setPush(t,value);else if(kind==1)queue.setPop(t);else queue.erase(t);};mutate(fixed);mutate(dynamic);mutate(compressed);mutate(monoid);checkQueue(fixed,order);checkQueue(dynamic,order);checkQueue(compressed,order);assert(fixed.sum()==dynamic.sum()&&fixed.sum()==compressed.sum());std::string fold;for(auto& e:fixed.debugOperations())if(e.kind==qdkPush&&fixed.isRemaining(e.time))fold+=std::to_string(*e.value)+",";assert(monoid.fold()==fold);}}
 for(auto order:{Ascending,Descending}){IndexedRetroactivePriorityQueue<Int> q(order);std::vector<Int> ids;for(int step=0;step<5000;++step){Int n=ids.size(),kind=rng()%5;if(!n||kind==0||kind==1){Int i=rng()%(n+1),id=kind==1?q.insertPop(i):q.insertPush(i,Int(rng()%11)-5);ids.insert(ids.begin()+i,id);}else{Int i=rng()%n;if(kind==2)q.setPush(i,Int(rng()%11)-5);else if(kind==3)q.setPop(i);else{Int id=ids[i];q.eraseById(id);ids.erase(ids.begin()+i);assert(q.indexOf(id)==-1);}}checkQueue(q,order);assert(q.operationCount()==Int(ids.size()));for(Int i=0;i<Int(ids.size());++i)assert(q.indexOf(ids[i])==i);auto ops=q.debugOperations();Int pushes=0,pops=0;for(Int i=0;i<Int(ops.size());++i)if(ops[i].kind==qdkPush)assert(q.pushIndex(pushes++)==i);else assert(q.popIndex(pops++)==i);assert(q.pushCount()==pushes&&q.popCount()==pops);}}
 for(Int n:{0,1,17,64}){std::vector<Int> keys(n);std::iota(keys.begin(),keys.end(),0);std::shuffle(keys.begin(),keys.end(),rng);std::vector<std::string> values(n);for(Int i=0;i<n;++i)values[i]=std::to_string(keys[i])+",";RangeSortArray a(keys,1000);auto s=initRangeSortSegmentTree(keys,values,1000,[](auto x,auto y){return x+y;},std::string{});std::vector<std::pair<Int,std::string>> ref;for(Int i=0;i<n;++i)ref.emplace_back(keys[i],values[i]);for(int q=0;q<1000;++q){Int l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);auto order=rng()%2?Ascending:Descending;Int kind=rng()%3;if(kind==0){a.sort(l,r,order);s.sort(l,r,order);std::sort(ref.begin()+l,ref.begin()+r,[&](auto x,auto y){return order==Ascending?x.first<y.first:x.first>y.first;});}else if(n&&kind==1){Int i=rng()%n,k=rng()%1000;bool duplicate=false;for(Int j=0;j<n;++j)if(j!=i&&ref[j].first==k)duplicate=true;if(!duplicate){std::string v="x"+std::to_string(k)+",";a.update(i,k);s.update(i,k,v);ref[i]={k,v};}}else if(n){Int i=rng()%n;ref[i].second="z";s.update(i,std::string("z"));}std::string product,all;std::vector<Int> expected;for(Int i=0;i<n;++i){expected.push_back(ref[i].first);assert(s.key(i)==ref[i].first&&s[i]==ref[i].second&&a[i]==ref[i].first);all+=ref[i].second;if(l<=i&&i<r)product+=ref[i].second;}assert(a.toSeq()==expected&&s.get(l,r)==product&&s.get_all()==all);}}
 for(Int size:{0,1,65,200}){IntSet s(closed_slice(-30,size-31));std::set<Int> ref;for(int q=0;q<1000;++q){Int x=Int(rng()%300)-60;if(x>=-30&&x<size-30&&rng()%2){assert(s.containsOrIncl(x)==ref.contains(x));ref.insert(x);}else{assert(s.missingOrExcl(x)==!ref.contains(x));ref.erase(x);}assert(s.len()==Int(ref.size()));std::set<Int> got;for(Int x:s)got.insert(x);assert(got==ref);if(!ref.empty()&&rng()%11==0){Int x=s.pop();assert(ref.erase(x));}}s.clear();assert(!s.len());}
 RadixHeap<Int,Int> h;std::multiset<Int> ref;Int last=std::numeric_limits<Int>::lowest();for(Int i=0;i<5000;++i){if(ref.empty()||rng()%2){Int x=last+Int(rng()%100000);h.push(x,i);ref.insert(x);}else{auto [x,v]=h.pop();(void)v;assert(x==*ref.begin());ref.erase(ref.begin());last=x;}}h.clear();h.push(std::numeric_limits<Int>::max(),0);assert(h.pop().first==std::numeric_limits<Int>::max());
 MaxHeapQueue<Int> heap;std::multiset<Int> expected;for(int i=0;i<3000;++i){Int x=rng()%100;if(expected.empty()||rng()%2){heap.push(x);expected.insert(x);}else{assert(heap.pop()==*expected.rbegin());expected.erase(std::prev(expected.end()));}if(heap.len()&&rng()%5==0){Int index=rng()%heap.len(),value=heap[index];heap.del(index);expected.erase(expected.find(value));}assert(heap.len()==Int(expected.size()));if(heap.len())assert(heap[0]==*expected.rbegin());}
}
