#include <cplib/str/static_string_search.hpp>
#include <cplib/str/double_ended_palindromic_tree.hpp>
#include <cplib/math/combination_arbitrary_mod.hpp>
#include <cplib/math/multiplicative_prefix_sum.hpp>
#include <cplib/math/stern_brocot_tree.hpp>
#include <cplib/utils/golden_section_search.hpp>
#include <cplib/utils/static_rectangle_add_rectangle_sum.hpp>
#include <random>
#include <set>
using namespace cplib;
int main(){std::mt19937_64 rng(111);
 for(int trial=0;trial<50;++trial){DoubleEndedPalindromicTree tree(3);std::string s;for(int step=0;step<500;++step){int kind=rng()%4;if(s.empty()||(s.size()<30&&kind<2)){char c='a'+rng()%3;if(kind%2){s+=c;tree.push_back(c);}else{s=c+s;tree.push_front(c);}}else if(kind%2){s.pop_back();tree.pop_back();}else{s.erase(s.begin());tree.pop_front();}std::set<std::string> distinct;Int total=0,pre=0,suf=0;for(Int l=0;l<Int(s.size());++l)for(Int r=l+1;r<=Int(s.size());++r){auto x=s.substr(l,r-l),y=x;std::reverse(y.begin(),y.end());if(x==y){distinct.insert(x);++total;if(!l)pre=std::max(pre,r-l);if(r==Int(s.size()))suf=std::max(suf,r-l);}}assert(tree.len()==Int(s.size())&&tree.count_palindromes()==total&&tree.count_distinct_palindromes()==Int(distinct.size())&&tree.longest_prefix_palindrome()==pre&&tree.longest_suffix_palindrome()==suf);}}
 for(Int n:{0,1,2,17,100,300}){std::string s(n,'a');for(auto& c:s)c='a'+rng()%4;auto whole=toStaticString(s);auto index=initStaticStringSearch(whole.base);for(int q=0;q<500;++q){Int a=rng()%(n+1),b=rng()%(n+1),c=rng()%(n+1),d=rng()%(n+1);if(a>b)std::swap(a,b);if(c>d)std::swap(c,d);auto text=whole.substr(a,b),pattern=whole.substr(c,d);std::vector<Int> expected,actual;for(Int i=a;i+d-c<=b;++i)if(s.compare(i,d-c,s,c,d-c)==0)expected.push_back(i-a);for(Int i:index.findAll(text,pattern))actual.push_back(i);assert(actual==expected);assert(index.count(text,pattern)==Int(expected.size())&&count(text,pattern)==Int(expected.size()));assert(index[text].contains(pattern)==!expected.empty());if(q%11==0)clearStaticStringSearchCache(whole.base);}clearStaticStringSearchCache();assert(index.count(whole,whole)==1);}
 for(Int n:{0,1,63,64,65,127,130,1000}){std::vector<Int> a(n);for(auto& x:a)x=rng()%100;StaticRMQ<Int> rmq(a);for(int q=0;q<1000;++q){Int l=rng()%(n+1),r=rng()%(n+1),lower=rng()%101,ll=r,rr=l;while(ll&&a[ll-1]>=lower)--ll;while(rr<n&&a[rr]>=lower)++rr;assert(rmq.minLeft(r,lower)==ll&&rmq.maxRight(l,lower)==rr);}}
 for(Int n:{0,1,100,2000}){std::vector<Int> a(n);for(auto& x:a)x=4096+rng()%128;WaveletMatrix wm(a,-1,true);for(int q=0;q<500;++q){Int l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);Int low=4090+rng()%160,high=low+Int(rng()%30);Int sum=0,count=0;for(Int i=l;i<r;++i)if(low<=a[i]&&a[i]<high){sum+=a[i];++count;}assert(wm.range_sum(l,r,low,high)==sum&&wm.range_freq(l,r,low,high)==count);assert(wm.range_sum_with_count(l,r,low,high)==(WaveletSumCount{sum,count}));}}
 for(Int m=1;m<=150;++m){CombinationArbitraryMod comb(100,m);std::vector<Int> row(102);row[0]=1%m;for(Int n=0;n<=100;++n){for(Int r=0;r<=n;++r)assert(comb.ncr(n,r)==row[r]);Int product=1%m;for(Int r=0;r<=n;++r){assert(comb.npr(n,r)==product);product=product*(n-r)%m;}for(Int r=n+1;r>0;--r)row[r]=(row[r]+row[r-1])%m;}}
 using M=StaticMontgomeryModint<998244353>;for(Int n:{0,1,100,4096,4097,10000,50000}){M expected=0;for(Int i=1;i<=n;++i){Int rest=i,phi=i;for(Int p=2;p*p<=rest;++p)if(rest%p==0){phi=phi/p*(p-1);while(rest%p==0)rest/=p;}if(rest>1)phi=phi/rest*(rest-1);expected+=phi;}auto result=multiplicativePrefixSum(n,std::vector<M>{M(-1),M(1)},[](Int p,Int e){return M(p).pow(e-1)*M(p-1);});assert(result==expected);assert(multiplicativePrefixSum(n,std::vector<M>{M(1)},[](Int,Int){return M(1);})==M(n));}
 constexpr auto inv=StaticBarrettModint<17>(6).divide_constant<3>();static_assert(inv.val()==2);constexpr auto inv2=StaticMontgomeryModint<17>(6).divide_constant<3>();static_assert(inv2.val()==2);
 for(Int l=-50;l<=50;l+=7)for(Int r=l;r<=70;r+=11)for(Int optimum=l-3;optimum<=r+3;++optimum){std::set<Int> seen;auto result=golden_section_search(l,r,[&](Int x){assert(seen.insert(x).second);assert(l<=x&&x<=r);return (x-optimum)*(x-optimum);});assert(result.x==std::clamp(optimum,l,r));}
 auto full=golden_section_search(std::numeric_limits<Int>::min(),std::numeric_limits<Int>::max(),[](Int x){return x<0?-__int128(x):__int128(x);});assert(full.x==0);auto f=golden_section_search(-10.,10.,[](double x){return (x-2)*(x-2);});assert(std::abs(f.x-2)<1e-6);
 const Int rooted[]={0,1,1,2,4,9,20,48,115,286},unrooted[]={0,1,1,1,2,3,6,11,23,47};for(Int n=1;n<=9;++n){Int count=0;for(auto& g:rooted_trees(n)){assert(g.len==n&&g.edge_count()==n-1);++count;}assert(count==rooted[n]);count=0;for(auto& g:unlabeled_trees(n)){(void)g;++count;}assert(count==unrooted[n]);}
 for(int trial=0;trial<200;++trial){std::vector<std::tuple<Int,Int,Int,Int,Int>> rectangles;std::vector<std::tuple<Int,Int,Int,Int>> queries;for(int i=0;i<20;++i){Int l=Int(rng()%21)-10,r=Int(rng()%21)-10,d=Int(rng()%21)-10,u=Int(rng()%21)-10;if(l>r)std::swap(l,r);if(d>u)std::swap(d,u);rectangles.emplace_back(l,d,r,u,Int(rng()%21)-10);queries.emplace_back(d,l,u,r);}auto ans=static_rectangle_add_rectangle_sum(rectangles,queries);for(Int i=0;i<Int(queries.size());++i){auto [a,b,c,d]=queries[i];Int expected=0;for(auto [l,y,r,z,w]:rectangles)expected+=std::max<Int>(0,std::min(c,r)-std::max(a,l))*std::max<Int>(0,std::min(d,z)-std::max(b,y))*w;assert(ans[i]==expected);}}
 {auto out=golden_section_search(std::int16_t(-100),std::int16_t(100),[](auto x){return Int(x)*x;});assert(out.x==0);}

}
