#include <cplib/utils/auto_rollback.hpp>
#include <cplib/utils/offline_dynamic_queries.hpp>
#include <cplib/utils/rollback_mo.hpp>
#include <cplib/utils/avx512utils.hpp>
#include <random>
#include <map>
using namespace cplib;
template<class T> void simd(std::mt19937_64& rng){using U=std::make_unsigned_t<T>;for(Int n:{0,1,7,8,9,31,32,33,63,64,65,127,128,129,255}){std::vector<T> a(n),b(n);for(auto& x:a)x=std::bit_cast<T>(U(rng()));for(auto& x:b)x=std::bit_cast<T>(U(rng()));auto add=avx512Add(a,b),sub=avx512Sub(a,b),lo=avx512Min(a,b),hi=avx512Max(a,b),an=avx512And(a,b),orr=avx512Or(a,b),xx=avx512Xor(a,b);for(Int i=0;i<n;++i){assert(add[i]==std::bit_cast<T>(U(U(a[i])+U(b[i]))));assert(sub[i]==std::bit_cast<T>(U(U(a[i])-U(b[i]))));assert(lo[i]==std::min(a[i],b[i])&&hi[i]==std::max(a[i],b[i]));assert(an[i]==T(a[i]&b[i])&&orr[i]==T(a[i]|b[i])&&xx[i]==T(a[i]^b[i]));}if(n){assert(avx512Min(a)==*std::min_element(a.begin(),a.end()));assert(avx512Max(a)==*std::max_element(a.begin(),a.end()));}avx512Add(a,b,a);assert(a==add);}std::array<T,3> a{T(1),T(2),T(3)},b{T(4),T(5),T(6)};static_assert(std::is_same_v<decltype(avx512Add(a,b)),std::array<T,3>>);assert(avx512Add(a,b)[2]==T(9));}
int main(){std::mt19937_64 rng(119);simd<std::int8_t>(rng);simd<std::uint8_t>(rng);simd<std::int16_t>(rng);simd<std::uint16_t>(rng);simd<std::int32_t>(rng);simd<std::uint32_t>(rng);simd<Int>(rng);simd<UInt>(rng);
 bool threw=false;try{avx512Min(std::vector<Int>{});}catch(const std::invalid_argument&){threw=true;}assert(threw);threw=false;try{avx512Add(std::vector<Int>{1},std::vector<Int>{});}catch(const std::invalid_argument&){threw=true;}assert(threw);
 Int x=1;withAutoRollback([&](auto& log,Int v){log.write(x)+=v;},[&](auto update,auto& log){auto p=log.snapshot();update(2);assert(x==3);update(5);log.rollback(p);assert(x==1);update(9);});assert(x==1);try{Temporary([&](auto& log){log.set(x,4);throw 1;});}catch(int){}assert(x==1);
 TemporaryRollbackLog log;TemporaryIndexCache cache;std::vector<Int> a(20);Temporary(log,[&](auto& h){h.set(x,2);h.set(x,3);assert(h.len()==1);for(int i=0;i<5;++i){h.rememberIndexed(&a[3],a.data(),a.size(),cache);a[3]++;}assert(h.len()==2);Temporary(h,[&](auto& h2){h2.set(x,7);h2.rememberIndexed(&a[3],a.data(),a.size(),cache);a[3]=9;});assert(x==3&&a[3]==5);});assert(x==1&&a[3]==0&&cache.owner==nullptr);
 for(int trial=0;trial<100;++trial){OfflineDynamicQueries<Int> solver;std::map<Int,Int> active;std::vector<Int> expected;for(int i=0;i<150;++i){Int t=rng()%20;if(rng()%3==0){Int sum=0;for(auto [k,v]:active){(void)k;sum+=v;}solver.output(expected.size());expected.push_back(sum);}else if(active.contains(t)){solver.remove(t);active.erase(t);}else{Int v=rng()%50;solver.add(t,v);active[t]=v;}}Int sum=0;std::vector<Int> history;solver.run([&](Int,Int v){history.push_back(sum);sum+=v;},[&]{sum=history.back();history.pop_back();},[&](Int q){assert(sum==expected[q]);});assert(sum==0&&history.empty());solver.runAutoRollback([&](auto& log,Int,Int v){log.write(sum)+=v;},[&](Int q){assert(sum==expected[q]);});assert(sum==0);try{solver.runAutoRollback([&](auto& log,Int,Int v){log.write(sum)+=v;},[&](Int){throw 1;});}catch(int){}assert(sum==0);}
 OfflineDynamicQueries<> empty;Int sum=0;empty.add(7);empty.output(0);empty.remove(7);empty.output(1);empty.runAutoRollback([&](auto& log,Int i){log.write(sum)+=i;},[&](Int i){assert(sum==(i?0:7));});assert(!sum);
 for(Int n:{0,1,17,100}){std::vector<Int> a(n);for(auto& x:a)x=rng()%100;RollbackMo mo(n,100);std::vector<Int> answers;for(int q=0;q<100;++q){Int l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);mo.insert(l,r);answers.push_back(std::accumulate(a.begin()+l,a.begin()+r,Int(0)));}Int sum=0;mo.runAutoRollback([&](auto& log,Int i){log.write(sum)+=a[i];},[&](Int q){assert(sum==answers[q]);});assert(sum==0);}
}
