#include <cplib/matrix/matrix.hpp>
#include <cplib/matrix/static_matrix.hpp>
#include <cplib/matrix/matops.hpp>
#include <cplib/modint/montgomery_impl.hpp>
#include <cplib/modint/barrett_impl.hpp>
#include <random>
#include <unordered_set>
using namespace cplib;
template<class T> T determinant_naive(const Matrix<T>& a){Int n=a.h();std::vector<Int> p(n);std::iota(p.begin(),p.end(),0);T sum=0;do{T product=1;int parity=0;for(Int i=0;i<n;++i){product*=a(i,p[i]);for(Int j=0;j<i;++j)parity^=p[j]>p[i];}sum+=parity?-product:product;}while(std::next_permutation(p.begin(),p.end()));return sum;}
template<class T> T hafnian_naive(const Matrix<T>& a,UInt mask){if(!mask)return T(1);Int i=std::countr_zero(mask);mask^=UInt(1)<<i;T result=0;for(Int j=i+1;j<a.h();++j)if(mask&(UInt(1)<<j))result+=a(i,j)*hafnian_naive(a,mask^(UInt(1)<<j));return result;}
template<class T> void fields(){std::mt19937 rng(89134);for(Int n=0;n<=6;++n)for(int trial=0;trial<80;++trial){Matrix<T> a(n,n,T(0));for(Int i=0;i<n;++i)for(Int j=0;j<n;++j)a(i,j)=T(rng()%7);T det=determinant_naive(a);assert(a.determinant()==det);auto inv=a.inverse();assert(bool(inv)==(det!=T(0)));if(inv)assert(a*(*inv)==Matrix<T>::identity(n));auto adj=a.adjugate();assert(a*adj==Matrix<T>::identity(n)*det);for(Int i=0;i<n;++i)for(Int j=0;j<n;++j){Matrix<T> minor(n-1,n-1,T(0));Int r=0;for(Int x=0;x<n;++x)if(x!=j){Int c=0;for(Int y=0;y<n;++y)if(y!=i)minor(r,c++)=a(x,y);++r;}T expected=determinant_naive(minor);if((i+j)&1)expected=-expected;assert(adj(i,j)==expected);}}
 for(Int n=0;n<=12;n+=2)for(int trial=0;trial<30;++trial){Matrix<T> a(n,n,T(0));for(Int i=0;i<n;++i)for(Int j=0;j<=i;++j)a(i,j)=a(j,i)=T(rng()%10);assert(a.hafnian()==hafnian_naive(a,(UInt(1)<<n)-1));}
 for(int trial=0;trial<400;++trial){Int h=rng()%9,w=rng()%9;Matrix<T> a(h,w,T(0));std::vector<T> x(w),b(h);for(auto& v:x)v=T(rng()%11);for(Int i=0;i<h;++i)for(Int j=0;j<w;++j){a(i,j)=T(rng()%11);b[i]+=a(i,j)*x[j];}auto solved=a.solveLinearSystem(b);assert(solved);assert(Int(solved->basis.size())==w-a.rank());auto evaluate=[&](const auto& v){std::vector<T> result(h);for(Int i=0;i<h;++i)for(Int j=0;j<w;++j)result[i]+=a(i,j)*v[j];return result;};assert(evaluate(solved->particular)==b);for(auto v:solved->basis)assert(evaluate(v)==std::vector<T>(h,T(0)));if(h&&w==0){b[0]=T(1);assert(!a.solveLinearSystem(b));}}
 StaticMatrix<5,6,T> fixed;fixed(0,0)=2;fixed(1,1)=3;fixed(0,1)=5;assert(fixed.rank()==2&&fixed.rank(1,3)==1&&fixed.determinant(2)==T(6));auto inverse=fixed.inverse(2);assert(inverse&&(*inverse)(0,0)==T(1)/T(2)&&(*inverse)(4,5)==T(0));auto adj=fixed.adjugate(2);assert(adj(0,0)==T(3)&&adj(0,1)==T(-5));assert(fixed.solveLinearSystem(std::vector<T>{7,9},2,2));}
int main(){fields<StaticMontgomeryModint<998244353>>();fields<StaticBarrettModint<1000000007>>();
 std::mt19937 rng(6743);for(int trial=0;trial<400;++trial){Int h=rng()%8,w=rng()%8,k=rng()%8;Matrix<Int> a(h,w,0),b(w,k,0);for(Int i=0;i<h;++i)for(Int j=0;j<w;++j)a(i,j)=Int(rng()%20)-10;for(Int i=0;i<w;++i)for(Int j=0;j<k;++j)b(i,j)=Int(rng()%20)-10;auto c=a*b;assert(c.h()==h&&c.w()==k);for(Int i=0;i<h;++i)for(Int j=0;j<k;++j){Int sum=0;for(Int p=0;p<w;++p)sum+=a(i,p)*b(p,j);assert(c(i,j)==sum);}auto minus=7-a;for(Int i=0;i<h;++i)for(Int j=0;j<w;++j){assert(minus(i,j)==7-a(i,j));assert((a>>1)(i,j)==(a(i,j)>>1));assert((a&3)(i,j)==(a(i,j)&3));}assert((a+a-a)==a&&a.sum()==(-(-a)).sum());}
 Matrix<Int> row(std::vector<Int>{2,3}),column(std::vector<Int>{2,3},true);assert(row.h()==1&&row.w()==2&&column.h()==2&&column.w()==1);Matrix<Int> empty_vertical(std::vector<Int>{},true);assert(empty_vertical.h()==0&&empty_vertical.w()==1);Matrix<Int> empty(0,8,0);assert((empty+empty).w()==8);std::unordered_set<Matrix<Int>> set;set.insert(row);assert(set.contains(row));
 auto a=initMatrix(std::array{std::array<Int,3>{1,2,3},std::array<Int,3>{4,5,6}});static_assert(std::is_same_v<decltype(a),StaticMatrix<2,3,Int>>);auto b=initMatrix<3,2>(Int(1));auto product=a*b;assert(product(0,0)==6&&product(1,1)==15);a[0]=std::array<Int,3>{7,8,9};a[1]=a[0];assert(a(1,2)==9);assert((10-a)(0,0)==3);assert(hash(a)==hash(a));
 Matrix<Int> fib(std::vector<std::vector<Int>>{{1,1},{1,0}});assert(fib.pow(10)(0,1)==55);auto fixed_fib=initMatrix(std::array{std::array<Int,2>{1,1},std::array<Int,2>{1,0}});assert(fixed_fib.pow(10)(0,1)==55);
 for(int trial=0;trial<400;++trial){Int h=rng()%7,w=rng()%7;Matrix<bool> a(h,w,false);std::vector<bool> b(h);for(Int i=0;i<h;++i){b[i]=rng()%2;for(Int j=0;j<w;++j)a(i,j)=rng()%2;}Int solutions=0;for(UInt mask=0;mask<(UInt(1)<<w);++mask){bool good=true;for(Int i=0;i<h;++i){bool sum=false;for(Int j=0;j<w;++j)sum^=a(i,j)&&((mask>>j)&1);good&=sum==b[i];}solutions+=good;}auto answer=a.solveLinearSystem(b);assert(bool(answer)==bool(solutions));if(answer)assert(solutions==(Int(1)<<answer->basis.size()));}
 assert((rotated(std::vector<std::string>{"ab","cd","ef"})==std::vector<std::string>{"eca","fdb"}));assert((transposed(std::vector<std::string>{"abc","def"})==std::vector<std::string>{"ad","be","cf"}));assert((trimmed(std::vector<std::string>{"0000","0100","0000"})==std::vector<std::string>{"1"}));assert(rotated(rotated(std::vector<std::string>{"ab"},-1),1)==std::vector<std::string>{"ab"});
}
