#include "scalar_matrix_reference.hpp"
#include <cplib/matrix/matrix_avx2.hpp>
#include <cplib/matrix/static_matrix_avx2.hpp>
#include <random>
#include <unordered_set>
using namespace cplib;
namespace av=cplib;
namespace st=cplib;
template<class A,class B> void equal(const A& a,const B& b){assert(a.h()==b.h()&&a.w()==b.w());for(Int i=0;i<a.h();++i)for(Int j=0;j<a.w();++j)assert(a(i,j)==b(i,j));}
template<class T> void products(){std::mt19937 rng(11291);for(auto shape:std::vector<std::array<Int,3>>{{0,0,5},{4,0,9},{0,2,0},{1,1,1},{3,7,9},{9,17,15},{39,63,65},{64,64,64},{65,65,65},{80,96,112},{129,131,137},{257,259,261}}){auto [h,w,k]=shape;scalar_reference::Matrix<T> a(h,w),b(w,k);av::Matrix<T> x(h,w),y(w,k);std::vector<std::uint32_t> aa(h*w),bb(w*k);for(Int i=0;i<h;++i)for(Int j=0;j<w;++j){aa[i*w+j]=rng()%T::umod();a(i,j)=x(i,j)=T(aa[i*w+j]);}for(Int i=0;i<w;++i)for(Int j=0;j<k;++j){bb[i*k+j]=rng()%T::umod();b(i,j)=y(i,j)=T(bb[i*k+j]);}auto c=a*b;equal(x*y,c);equal(av::matrixProduct(x,y),c);auto cur=av::matrixProduct(aa,bb,h,w,k,T::umod());for(Int i=0;i<h;++i)for(Int j=0;j<k;++j)assert(cur[i*k+j]==c(i,j).val());}}
template<class T> void fields(){std::mt19937 rng(9374);for(Int n=0;n<=35;++n)for(int trial=0;trial<5;++trial){av::Matrix<T> a(n,n);scalar_reference::Matrix<T> ref(n,n);for(Int i=0;i<n;++i)for(Int j=0;j<n;++j)a(i,j)=ref(i,j)=T(rng()%7);if(trial==1&&n)for(Int j=0;j<n;++j)a(0,j)=ref(0,j)=0;if(trial==2&&n>1)for(Int j=0;j<n;++j)a(0,j)=ref(0,j)=a(1,j);assert(a.determinant()==ref.determinant());assert(a.rank()==ref.rank());equal(a.adjugate(),ref.adjugate());auto inv=a.inverse();auto ir=ref.inverse();assert(bool(inv)==bool(ir));if(inv)equal(*inv,*ir);}
 for(Int n=0;n<=16;n+=2){av::Matrix<T> a(n,n);scalar_reference::Matrix<T> ref(n,n);for(Int i=0;i<n;++i)for(Int j=0;j<=i;++j)a(i,j)=a(j,i)=ref(i,j)=ref(j,i)=T(rng()%13);assert(a.hafnian()==ref.hafnian());}
 for(int trial=0;trial<400;++trial){Int h=rng()%34,w=rng()%34;av::Matrix<T> a(h,w);scalar_reference::Matrix<T> ref(h,w);std::vector<T> rhs(h);for(Int i=0;i<h;++i){rhs[i]=T(rng()%7);for(Int j=0;j<w;++j)a(i,j)=ref(i,j)=T(rng()%7);}auto s=a.solveLinearSystem(rhs),r=ref.solveLinearSystem(rhs);assert(bool(s)==bool(r));if(s){assert(s->particular==r->particular&&s->basis==r->basis);}}
 st::StaticMatrix<19,23,T> fixed;scalar_reference::Matrix<T> ref(19,23);for(Int i=0;i<19;++i)for(Int j=0;j<23;++j)fixed(i,j)=ref(i,j)=T(rng()%19);assert(fixed.rank()==ref.rank());for(Int n=0;n<=19;++n){scalar_reference::Matrix<T> sub(n,n);for(Int i=0;i<n;++i)for(Int j=0;j<n;++j)sub(i,j)=fixed(i,j);assert(fixed.determinant(n)==sub.determinant());auto adj=fixed.adjugate(n);auto expected=sub.adjugate();for(Int i=0;i<19;++i)for(Int j=0;j<23;++j)assert(adj(i,j)==(i<n&&j<n?expected(i,j):T(0)));auto inv=fixed.inverse(n);auto ir=sub.inverse();assert(bool(inv)==bool(ir));if(inv)for(Int i=0;i<n;++i)for(Int j=0;j<n;++j)assert((*inv)(i,j)==(*ir)(i,j));std::vector<T> rhs(n,T(3));auto s=fixed.solveLinearSystem(rhs,n,n),r=sub.solveLinearSystem(rhs);assert(bool(s)==bool(r));if(s)assert(s->particular==r->particular&&s->basis==r->basis);}
 st::StaticMatrix<18,20,T> sym;scalar_reference::Matrix<T> sr(18,18);for(Int i=0;i<18;++i)for(Int j=0;j<=i;++j)sym(i,j)=sym(j,i)=sr(i,j)=sr(j,i)=T(rng()%7);assert(sym.hafnian(18)==sr.hafnian());
}
template<class T> void interface(){std::vector<std::uint32_t> raw{1,9,9999,10000,99999999,100000000};const void* address=raw.data();av::Matrix<T> a(2,3,std::move(raw));assert(static_cast<const void*>(&a(0,0))==address);assert(a[0].join(",")=="1,9,9999");assert(a[1].join("::")=="10000::99999999::100000000");auto row=a[1];auto copy=a;row[from_end(1)]=7;assert(a(1,2)==7&&copy(1,2)==100000000);a=av::Matrix<T>(1,1);assert(row[0]==10000);for(auto& x:row.mitems())x+=1;assert(row[from_end(1)]==8);for(auto [i,x]:row.pairs())assert(x==row[i]);auto seq=row.toSeq();assert(seq[2]==8);
 const auto& ccopy=copy;auto read=ccopy[0];copy[1]=read;assert(copy[1].toSeq()==read.toSeq());copy[0]=std::vector<T>{4,5,6};assert(copy(0,0)==4);std::vector<T> owned{1,2,3};address=owned.data();av::Matrix<T> moved(1,3,std::move(owned));assert(static_cast<const void*>(&moved(0,0))==address);assert(av::Matrix<T>(std::vector<T>{1,2},true).h()==2);av::Matrix<T> fromspan(1,3,std::span<const std::uint32_t>(std::array<std::uint32_t,3>{4,5,6}));assert(fromspan(0,2)==6);
 av::Matrix<T> fib(std::vector<std::vector<T>>{{1,1},{1,0}});assert(fib.pow(10)(0,1)==55);assert(fib.pow(0)==av::Matrix<T>::identity(2));assert(fib.pow(1)==fib);assert(((fib+3)-3)==fib);assert((UInt(-1)*fib)(0,0)==T(UInt(-1)));assert((5-fib)(0,0)==4);assert((-fib+fib).sum()==0);std::unordered_set<av::Matrix<T>> set;set.insert(fib);assert(set.contains(fib));
 std::vector<T> large(2051);std::string expected;for(Int i=0;i<Int(large.size());++i){large[i]=T(UInt(i)*7919);if(i)expected+=' ';expected+=std::to_string(large[i].val());}av::Matrix<T> line(1,large.size(),large);FILE* f=std::tmpfile();assert(f);line[0].writeRow(f);std::rewind(f);std::string output(expected.size()+1,'\0');assert(std::fread(output.data(),1,output.size(),f)==output.size());assert(output==expected+'\n');std::fclose(f);
 st::StaticMatrix<2,2,T> tiny; tiny[0]=std::array<T,2>{1,1};tiny[1]=std::array<T,2>{1,0};assert(tiny.pow(10)(0,1)==55);assert((tiny+tiny-tiny)==tiny);assert((-tiny+tiny).sum()==0);st::StaticMatrix<5,7,T> x(T(2));st::StaticMatrix<7,9,T> y(T(3));auto z=x*y;for(Int i=0;i<5;++i)for(Int j=0;j<9;++j)assert(z(i,j)==42);
}
int main(){using M=StaticMontgomeryModint<998244353>;using B=StaticBarrettModint<1000000007>;products<M>();products<B>();fields<M>();fields<B>();interface<M>();interface<B>();using D=DynamicMontgomeryModint<981>;D::setMod(1073741789);products<D>();D::setMod(3);products<D>();D::setMod(1);products<D>();using DB=DynamicBarrettModint<982>;DB::setMod(1);products<DB>();av::Matrix<M> zero(3,0);assert(zero.str()=="\n\n"&&zero[0].join()=="");assert(zero[0].toSeq().empty());st::StaticMatrix<0,3,M> empty;assert(empty.rank()==0&&empty.determinant(0)==1);}
