#include <cplib/collections/segtree_beats_template.hpp>
#include <random>
using namespace cplib;
template<class T> void check(){std::mt19937 rng(38745);for(Int n:{0,1,2,3,17,127,1000}){std::vector<T> a(n);for(auto& x:a)x=T(Int(rng()%200)-100);auto tree=initRangeChminChmaxRangeSumMaxMin(a);for(int q=0;q<2500;++q){Int l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);T value=T(Int(rng()%200)-100);switch(rng()%5){case 0:tree.chmin(closed_slice(l,r-1),value);for(Int i=l;i<r;++i)a[i]=std::min(a[i],value);break;case 1:tree.chmax(l,r,value);for(Int i=l;i<r;++i)a[i]=std::max(a[i],value);break;case 2:tree.add(l,r,value);for(Int i=l;i<r;++i)a[i]+=value;break;case 3:if(l<n){tree[l]=value;a[l]=value;}break;default:break;}auto got=tree[closed_slice(l,r-1)];T sum=0;for(Int i=l;i<r;++i)sum+=a[i];assert(got.sum==sum&&got.sz==r-l);if(l<r){T lo=*std::min_element(a.begin()+l,a.begin()+r),hi=*std::max_element(a.begin()+l,a.begin()+r);assert(got.min==lo&&got.max==hi);assert(got.n_min==std::count(a.begin()+l,a.begin()+r,lo)&&got.n_max==std::count(a.begin()+l,a.begin()+r,hi));}if(n&&q%30==0)assert(tree[from_end(1)].sum==a.back());}auto copy=tree;if(n){copy.update(0,T(234));assert(tree.get(0).sum==a[0]);}assert(!tree.str().empty()||n==0);}}
struct DivNode{Int sum=0,min=1000000000,max=0,size=0;bool fail=false;};
int main(){check<Int>();check<std::int32_t>();check<double>();
 auto op=[](DivNode a,DivNode b){return DivNode{a.sum+b.sum,std::min(a.min,b.min),std::max(a.max,b.max),a.size+b.size,false};};auto map=[](Int f,DivNode x){if(x.size&&f!=1){if(x.min/f==x.max/f){x.min/=f;x.max/=f;x.sum=x.min*x.size;x.fail=false;}else x.fail=true;}return x;};auto comp=[](Int a,Int b){return std::min<Int>(1000000000,a*b);};std::mt19937 rng(982347);std::vector<Int> a(103);std::vector<DivNode> nodes;for(auto& x:a){x=rng()%1000000;nodes.push_back({x,x,x,1,false});}auto tree=initSegmentTreeBeats<DivNode,Int>(nodes,op,DivNode{},map,comp,Int(1));for(Int q=0;q<3000;++q){Int l=rng()%104,r=rng()%104;if(l>r)std::swap(l,r);if(q%4){Int d=2+rng()%8;tree.apply(l,r,d);for(Int i=l;i<r;++i)a[i]/=d;}else if(l<103){a[l]=rng()%1000000;tree[l]=DivNode{a[l],a[l],a[l],1,false};}assert(tree.get(l,r).sum==std::accumulate(a.begin()+l,a.begin()+r,Int(0)));}
 initSegmentTreeBeatsInPlace(tree,Int(10),op,DivNode{},map,comp,Int(1));for(Int i=0;i<10;++i)tree[i]=DivNode{i,i,i,1,false};assert(tree.get(0,10).sum==45);
}
