#include <cplib/collections/bitset_avx512.hpp>
#include <random>
using namespace cplib;
template<class B> void test(Int n){std::mt19937 rng(n);for(int trial=0;trial<50;++trial){std::vector<bool> a(n),b(n),c(n);for(Int i=0;i<n;++i){a[i]=rng()%2;b[i]=rng()%2;c[i]=rng()%2;}B x(a),y(b),z(c);auto check=[&](const B& value,const std::vector<bool>& v){assert(value.len()==n);Int count=0,first=-1;std::vector<Int> indices;for(Int i=0;i<n;++i){assert(value[i]==v[i]);count+=v[i];if(v[i]){indices.push_back(i);if(first==-1)first=i;}}assert(value.popcount()==count&&value.lowestBit()==first&&value.all()==(count==n)&&value.any()==bool(count));std::vector<Int> actual;for(Int i:value)actual.push_back(i);assert(actual==indices);};auto combine=[&](auto fn){std::vector<bool> out(n);for(Int i=0;i<n;++i)out[i]=fn(bool(a[i]),bool(b[i]),bool(c[i]));return out;};check(x,a);check(x&y,combine([](bool a,bool b,bool){return a&&b;}));check(x|y,combine([](bool a,bool b,bool){return a||b;}));check(x^y,combine([](bool a,bool b,bool){return a!=b;}));check(~x,combine([](bool a,bool,bool){return !a;}));auto dst=x;dst.andNotAssign(y);check(dst,combine([](bool a,bool b,bool){return a&&!b;}));dst=x;dst.selectAssign(y,z);check(dst,combine([](bool a,bool b,bool c){return c?b:a;}));dst=x;dst.orAndAssign(y,z);check(dst,combine([](bool a,bool b,bool c){return a||(b&&c);}));dst=x;dst.andOrAssign(y,z);check(dst,combine([](bool a,bool b,bool c){return a&&(b||c);}));dst=x;dst.xorAndAssign(y,z);check(dst,combine([](bool a,bool b,bool c){return a!=(b&&c);}));check(x.majority(y,z),combine([](bool a,bool b,bool c){return Int(a)+b+c>=2;}));check(x.xnor(y),combine([](bool a,bool b,bool){return a==b;}));dst=x;dst.xnorInto(dst,y);assert(dst==x.xnor(y));dst=x;dst.andInto(dst,y);assert(dst==(x&y));dst=x;dst.orInto(y,dst);assert(dst==(x|y));dst=x;dst.xorInto(dst,dst);assert(!dst.any());
        assert(x.andpopcount(y)==(x&y).popcount()&&x.orpopcount(y)==(x|y).popcount()&&x.xorpopcount(y)==(x^y).popcount()&&x.xnorpopcount(y)==n-(x^y).popcount());assert(x.intersects(y)==(x&y).any());assert(x.isSubsetOf(y)==((x&y)==x));assert((x<y)==std::lexicographical_compare(a.begin(),a.end(),b.begin(),b.end()));
        for(Int shift:std::array<Int,9>{0,1,63,64,65,255,256,n,n+1}){std::vector<bool> left(n),right(n);for(Int i=0;i<n;++i){if(i+shift<n)left[i+shift]=a[i];if(i>=shift)right[i-shift]=a[i];}check(x<<shift,left);check(x>>shift,right);if constexpr(requires(B v){v<<=shift;}){dst=x;dst<<=shift;check(dst,left);dst=x;dst>>=shift;check(dst,right);for(Int i=0;i<n;++i){left[i]=left[i]||a[i];right[i]=right[i]||a[i];}dst=x;dst.orShiftLeftAssign(shift);check(dst,left);dst=x;dst.orShiftRightAssign(shift);check(dst,right);}}
        for(int q=0;q<30;++q){Int l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);Int ac=0,bc=0,oc=0,xc=0;for(Int i=l;i<r;++i){ac+=a[i];bc+=a[i]&&b[i];oc+=a[i]||b[i];xc+=a[i]!=b[i];}assert(x.popcountrange(l,r)==ac&&x.andpopcountrange(y,l,r)==bc&&x.orpopcountrange(y,l,r)==oc&&x.xorpopcountrange(y,l,r)==xc);auto expected=a;dst=x;dst.setRange(l,r);for(Int i=l;i<r;++i)expected[i]=true;check(dst,expected);dst=x;dst.clearRange(l,r);for(Int i=l;i<r;++i)expected[i]=false;check(dst,expected);dst=x;dst.flipRange(l,r);for(Int i=l;i<r;++i)expected[i]=!a[i];check(dst,expected);Int next=-1,prev=-1;for(Int i=l;i<n;++i)if(a[i]){next=i;break;}for(Int i=r;i-->0;)if(a[i]){prev=i;break;}assert(x.nextSetBit(l)==next&&x.prevSetBit(r-1)==prev);}
        if constexpr(requires(B v){v.andAssignPopcount(y);}){auto run=[&](auto update,const B& want){dst=x;assert(update(dst)==want.popcount());assert(dst==want);};run([&](B& v){return v.andAssignPopcount(y);},x&y);run([&](B& v){return v.orAssignPopcount(y);},x|y);run([&](B& v){return v.xorAssignPopcount(y);},x^y);run([&](B& v){return v.andNotAssignPopcount(y);},x&~y);run([&](B& v){return v.selectAssignPopcount(y,z);},(x&~z)|(y&z));run([&](B& v){return v.orAndAssignPopcount(y,z);},x|(y&z));run([&](B& v){return v.andOrAssignPopcount(y,z);},x&(y|z));run([&](B& v){return v.xorAndAssignPopcount(y,z);},x^(y&z));run([&](B& v){return v.xnorAssignPopcount(y);},~(x^y));std::vector<bool> sum(n);bool carry=false;for(Int i=0;i<n;++i){Int t=Int(a[i])+b[i]+carry;sum[i]=t&1;carry=t>=2;}check(x+y,sum);dst=x;dst+=y;check(dst,sum);assert(x.lastBit()==(n&&a.back()));}
        std::string str(n,'a'),ref(n,'a');for(char& v:str)v=char(rng()%4);for(char& v:ref)v=char(rng()%4);dst.fromString(str,'\0');std::vector<bool> expected(n);for(Int i=0;i<n;++i)expected[i]=str[i]=='\0';check(dst,expected);dst.fromString(str,ref);for(Int i=0;i<n;++i)expected[i]=str[i]==ref[i];check(dst,expected);dst.clear();assert(!dst.any());dst.fill();assert(dst.all());dst.flipAll();assert(!dst.any());if(n){dst[n-1]=1;assert(dst[from_end(1)]);dst[n-1]=2;assert(dst[n-1]);dst.flip(n-1);assert(!dst.any());}}
}
int main(){for(Int n:{0,1,63,64,65,255,256,257,1024,10003}){test<SimdBitSet<2>>(n);test<BitSetAvx512>(n);}test<SimdBitSet<2,0>>(0);test<SimdBitSet<512,0>>(0);test<SimdBitSet<2,1003>>(1003);test<SimdBitSet<512,1003>>(1003);test<SimdBitSet<2,10003>>(10003);test<SimdBitSet<512,10003>>(10003);
    auto b=cplib::initBitSetFromString("aab",'a',20);assert(b.popcount()==2);
    // 長い全ビット1区間を越える桁上がりと、ゼロ語を飛ばす探索を確認。
    for(Int n:{513,1024,10003}){BitSetAvx512 ones(n),one(n);ones.fill();one[0]=true;assert(!(ones+one).any());ones[n-1]=false;auto sum=ones+one;assert(sum.popcount()==1&&sum[n-1]);}
    auto sparse=[]<class B>(B x){for(Int i:{0,511,512,8192,10002})x[i]=true;std::vector<Int> got;for(Int i:x)got.push_back(i);assert((got==std::vector<Int>{0,511,512,8192,10002}));for(Int i=0;i<x.len();++i){auto it=std::lower_bound(got.begin(),got.end(),i);assert(x.nextSetBit(i)==(it==got.end()?-1:*it));auto jt=std::upper_bound(got.begin(),got.end(),i);assert(x.prevSetBit(i)==(jt==got.begin()?-1:*--jt));}};
    sparse(SimdBitSet<2>(10003));sparse(BitSetAvx512(10003));
    bool values[]{true,false,true};SimdBitSet<2,1003> sa{std::span<const bool>(values)};SimdBitSet<512,1003> sb{std::span<const bool>(values)};assert(sa.popcount()==2&&sb.popcount()==2);
}
