#include <cplib/str/static_string.hpp>
#include <cplib/str/merged_static_string.hpp>
#include <cplib/str/repeated_static_string.hpp>
#include <random>
using namespace cplib;
Int naive_lcp(const std::string& a,const std::string& b){Int i=0;while(i<Int(std::min(a.size(),b.size()))&&a[i]==b[i])++i;return i;}
int main(){std::mt19937 rng(35);
    for(Int n:{0,1,2,3,15,64,100,1000})for(int trial=0;trial<10;++trial){std::string text(n,'a');for(char& c:text)c=trial%2?char(rng()%256):char('a'+rng()%4);auto s=toStaticString(text,true),plain=toStaticString(text);std::vector<StaticString<char>> parts;
        for(int q=0;q<500;++q){Int a=rng()%(n+1),b=rng()%(n+1),c=rng()%(n+1),d=rng()%(n+1);if(a>b)std::swap(a,b);if(c>d)std::swap(c,d);auto x=s.substr(a,b),y=s.substr(c,d);auto u=text.substr(a,b-a),v=text.substr(c,d-c);assert(x.to_string()==u&&y.to_string()==v);assert(lcp(x,y)==naive_lcp(u,v));assert((x<y)==(u<v)&&(x==y)==(u==v));std::reverse(u.begin(),u.end());std::reverse(v.begin(),v.end());assert(x.reversed().to_string()==u&&lcs(x,y)==naive_lcp(u,v));assert(x.isPalindrome()==(x.to_string()==u));assert(startsWith(x,y)==x.to_string().starts_with(y.to_string()));parts.push_back(x);
            auto fixed=x&y&x;auto merged=mergeStaticStrings(x,y)&x;std::string joined=x.to_string()+y.to_string()+x.to_string();assert(fixed.to_string()==joined&&merged.to_string()==joined&&fixed.len()==Int(joined.size())&&merged.len()==Int(joined.size()));Int l=rng()%(joined.size()+1),r=rng()%(joined.size()+1);if(l>r)std::swap(l,r);auto fs=fixed[closed_slice(l,r-1)];auto ms=merged[closed_slice(l,r-1)];assert(fs.to_string()==joined.substr(l,r-l)&&ms.to_string()==joined.substr(l,r-l));assert(lcp(fixed,fs)==naive_lcp(joined,joined.substr(l,r-l)));assert(lcp(merged,ms)==lcp(fixed,fs));assert((merged<ms)==(joined<joined.substr(l,r-l))&&(fixed<fs)==(merged<ms));if(!joined.empty()){Int i=rng()%joined.size();assert(fixed[from_end(joined.size()-i)]==joined[i]&&merged[i]==joined[i]);}
            Int lenx=x.len()?rng()%500:0,leny=y.len()?rng()%500:0;auto rx=initRepeatedStaticString(x,lenx),ry=initRepeatedStaticString(y,leny);std::string ex,ey;for(Int i=0;i<lenx;++i)ex+=x[i%x.len()];for(Int i=0;i<leny;++i)ey+=y[i%y.len()];assert(rx.to_string()==ex&&ry.to_string()==ey);assert(lcp(rx,ry)==naive_lcp(ex,ey)&&(rx<ry)==(ex<ey)&&(rx==ry)==(ex==ey));assert(lcp(rx,y)==naive_lcp(ex,y.to_string())&&(rx<y)==(ex<y.to_string())&&(y<rx)==(y.to_string()<ex));
            auto pattern=x.to_string();Int count=0;for(Int i=0;i<n;++i)count+=text.substr(i).starts_with(pattern);assert(plain.base->count(pattern)==count);
        }
        auto expected=parts;std::stable_sort(expected.begin(),expected.end(),[](const auto& a,const auto& b){return a.to_string()<b.to_string();});sortStaticStrings(parts);for(std::size_t i=0;i<parts.size();++i)assert(parts[i].l==expected[i].l&&parts[i].r==expected[i].r);auto suffixes=initSuffixArray(s.base);std::vector<std::string> suffixStrings;for(Int i=0;i<n;++i)suffixStrings.push_back(text.substr(i));std::sort(suffixStrings.begin(),suffixStrings.end());for(Int i=0;i<n;++i)assert(suffixes[i].to_string()==suffixStrings[i]);auto suffixes2=initSuffixArray(s);assert(suffixes==suffixes2);
    }
    auto periods=toStaticStrings({"ab","abab","aba",""},true);auto a=initRepeatedStaticString(periods[0],1000000000000LL),b=initRepeatedStaticString(periods[1],1000000000000LL),c=initRepeatedStaticString(periods[2],1000000000000LL);assert(lcp(a,b)==1000000000000LL&&lcp(a,c)==3);auto integral=toStaticString(std::vector<Int>{100000000000LL,-4,100000000000LL},true);assert(integral.isPalindrome()&&integral.to_string()=="100000000000 -4 100000000000");FixedLengthMergedStaticString<char,0> empty;auto f=empty&periods[0];assert(f.to_string()=="ab"&&lcp(empty,f)==0);auto ff=f&f;assert(ff.to_string()=="abab");
}
