#include <cplib/collections/wordsizetree.hpp>
#include <memory>
#include <set>
#include <cplib/collections/bitvector.hpp>
#include <cplib/collections/fenwick_avx2.hpp>
#include <cplib/collections/waveletmatrix.hpp>
#include <cplib/collections/waveletmatrix_fenwick.hpp>
#include <cplib/collections/staticrangecount.hpp>
#include <random>
using namespace cplib;

int main(){
    std::mt19937_64 rng(41);
    for(Int n:{0,1,15,16,17,63,64,65,255,256,257,4096,10000}){auto bv=newBitVector(n);std::vector<Int> a(n);Int total=0;for(Int i=0;i<n;++i)if(rng()%2){bv.set(i);a[i]=1;}bv.build();for(Int i=0;i<=n;++i){assert(bv.rank(i)==total);if(i<n){assert(bv[i]==bool(a[i]));total+=a[i];}}for(auto& x:a)x=std::bit_cast<Int>(rng());auto ft=initFenwickTreeAvx2(a);auto copy=ft;for(int q=0;q<500;++q){if(n&&rng()%2){Int p=rng()%n,value=std::bit_cast<Int>(rng());if(rng()%2){ft[p]=value;a[p]=value;}else{ft.add(p,value);a[p]=std::bit_cast<Int>(UInt(a[p])+UInt(value));}}Int l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);UInt sum=0;for(Int i=l;i<r;++i)sum+=UInt(a[i]);assert(ft.get(l,r)==std::bit_cast<Int>(sum));if(l==0)assert(ft.prefix(r)==std::bit_cast<Int>(sum));if(n)assert(Int(ft[from_end(1)])==a.back());}if(n){Int original=copy[0];ft[0]=123;assert(Int(copy[0])==Int(original));}}
    for(int mode=0;mode<4;++mode)for(int trial=0;trial<100;++trial){Int n=rng()%400;std::vector<Int> v(n);for(auto& x:v)x=mode==0?0:mode==1?rng()%16:mode==2?rng()%1000000:rng()%1000000000000LL;auto w=initWaveletMatrix(v,-1,true);auto explicitHeight=initWaveletMatrix(v,64,true);auto noSum=initWaveletMatrix(v);auto counts=initStaticRangeCount(v);for(int q=0;q<250;++q){Int l=rng()%(n+1),r=rng()%(n+1);if(l>r)std::swap(l,r);std::vector<Int> sorted(v.begin()+l,v.begin()+r);std::sort(sorted.begin(),sorted.end());Int x=Int(rng()%1000001)-1;if(q%3==0&&n)x=v[rng()%n];if(q%41==0)x=std::numeric_limits<Int>::max();Int lower=std::lower_bound(sorted.begin(),sorted.end(),x)-sorted.begin(),upper=std::upper_bound(sorted.begin(),sorted.end(),x)-sorted.begin();assert(w.range_lowerbound(l,r,x)==lower&&w.range_upperbound(l,r,x)==upper&&w.count(l,r,x)==upper-lower);assert(noSum.range_lowerbound(l,r,x)==lower&&explicitHeight.range_upperbound(l,r,x)==upper);assert(counts.count(l,r,x)==upper-lower);if(l<r)assert(counts.count(closed_slice(l,r-1),x)==upper-lower);std::optional<Int> prev=lower?std::optional<Int>(sorted[lower-1]):std::nullopt,next=lower<Int(sorted.size())?std::optional<Int>(sorted[lower]):std::nullopt;assert(w.prev_value(l,r,x)==prev&&w.next_value(l,r,x)==next);Int k=rng()%(r-l+1),sum=std::accumulate(sorted.begin(),sorted.begin()+k,Int(0));assert(w.sum_smallest(l,r,k)==sum&&explicitHeight.sum_smallest(l,r,k)==sum);assert((w.sum_smallest_with_count(l,r,k)==WaveletSumCount{sum,k}));Int lowSum=std::accumulate(sorted.begin(),sorted.begin()+lower,Int(0)),upSum=std::accumulate(sorted.begin(),sorted.begin()+upper,Int(0));assert(w.sum_lowerbound(l,r,x)==lowSum&&w.sum_upperbound(l,r,x)==upSum);assert((w.sum_upperbound_with_count(l,r,x)==WaveletSumCount{upSum,upper}));assert((w.sum_lowerbound_with_count(l,r,x)==WaveletSumCount{lowSum,lower}));if(l<r){Int rank=rng()%(r-l);assert(w.kth_smallest(l,r,rank)==sorted[rank]&&w.kth_largest(l,r,rank)==sorted[r-l-1-rank]);}Int lo=Int(rng()%10000)-10,hi=Int(rng()%10000)-10;WaveletSumCount want;for(Int a:sorted)if(lo<=a&&a<hi){want.sum+=a;++want.count;}assert(w.range_freq(l,r,lo,hi)==want.count&&w.range_sum(l,r,lo,hi)==want.sum&&w.range_sum_with_count(l,r,lo,hi)==want);}}
    for(int trial=0;trial<150;++trial){Int n=rng()%200;std::vector<std::pair<Int,Int>> v(n);for(auto& [x,w]:v){x=Int(rng()%100)-50;w=Int(rng()%100)-50;}auto wm=initWaveletMatrixFenwick(v);for(int q=0;q<300;++q){if(n&&rng()%3==0){Int i=rng()%n,delta=Int(rng()%100)-50;if(q%2){wm.add(i,delta);v[i].second+=delta;}else{wm[i]=delta;v[i].second=delta;}assert(Int(wm[i])==v[i].second&&Int(wm[from_end(n-i)])==v[i].second);}Int l=rng()%(n+1),r=rng()%(n+1),lo=Int(rng()%150)-75,hi=Int(rng()%150)-75;if(l>r)std::swap(l,r);if(lo>hi)std::swap(lo,hi);Int all=0,less=0,between=0;for(Int i=l;i<r;++i){auto [x,w]=v[i];all+=w;if(x<=hi)less+=w;if(lo<=x&&x<hi)between+=w;}assert(wm.range_sum(l,r)==all&&wm.range_sum(l,r,hi)==less&&wm.range_sum(l,r,lo,hi)==between);}}
}
