#pragma once
#include <cplib/convolution/convolution.hpp>
#include <compare>
#include <memory>
#include <stdexcept>
#include <ostream>
namespace cplib {
class BigInt;
template<class T,class R=T> struct QuotientRemainder {T quotient;R remainder;};
using BigIntDivision=QuotientRemainder<BigInt>;
class BigInt {
 int sign_=0;std::vector<std::uint32_t> digits_;
 static constexpr UInt Base=1000000000,Mod1=754974721,Mod2=469762049,InvMod1=221064492;
 static constexpr Int NttThreshold=64,NttMaxLength=Int(1)<<24,LargeBaseMaxDigits=(Mod1*Mod2-1)/(UInt(999999)*999999),NewtonThreshold=256;
 void normalize(){while(!digits_.empty()&&!digits_.back())digits_.pop_back();if(digits_.empty())sign_=0;}
 static int cmpAbs(const BigInt& a,const BigInt& b){if(a.digits_.size()!=b.digits_.size())return a.digits_.size()<b.digits_.size()?-1:1;for(Int i=Int(a.digits_.size())-1;i>=0;--i)if(a.digits_[i]!=b.digits_[i])return a.digits_[i]<b.digits_[i]?-1:1;return 0;}
 static BigInt addAbs(const BigInt& a,const BigInt& b){BigInt out;out.sign_=1;Int n=std::max(a.digits_.size(),b.digits_.size());out.digits_.resize(n+1);UInt carry=0;for(Int i=0;i<n;++i){if(i<Int(a.digits_.size()))carry+=a.digits_[i];if(i<Int(b.digits_.size()))carry+=b.digits_[i];out.digits_[i]=carry%Base;carry/=Base;}out.digits_[n]=carry;out.normalize();return out;}
 static BigInt subAbs(const BigInt& a,const BigInt& b){BigInt out;out.sign_=1;out.digits_.resize(a.digits_.size());Int borrow=0;for(Int i=0;i<Int(a.digits_.size());++i){Int digit=Int(a.digits_[i])-borrow;if(i<Int(b.digits_.size()))digit-=b.digits_[i];borrow=0;if(digit<0){digit+=Base;borrow=1;}out.digits_[i]=digit;}out.normalize();return out;}
 std::vector<std::uint32_t> binaryDigits()const{std::vector<std::uint32_t> out;for(Int i=Int(digits_.size())-1;i>=0;--i){UInt carry=digits_[i];for(auto& d:out){UInt value=UInt(d)*Base+carry;d=std::uint32_t(value);carry=value>>32;}if(carry)out.push_back(carry);}return out;}
 static BigInt fromBinary(const std::vector<std::uint32_t>& digits){BigInt out;out.sign_=1;for(Int i=Int(digits.size())-1;i>=0;--i){UInt carry=digits[i];for(auto& d:out.digits_){UInt value=(UInt(d)<<32)+carry;d=value%Base;carry=value/Base;}while(carry){out.digits_.push_back(carry%Base);carry/=Base;}}out.normalize();return out;}
 static void complement(std::vector<std::uint32_t>& digits){UInt carry=1;for(auto& d:digits){UInt value=UInt(~d)+carry;d=std::uint32_t(value);carry=value>>32;}}
 template<int Op> static BigInt bitwise(const BigInt& a,const BigInt& b){auto left=a.binaryDigits(),right=b.binaryDigits();auto size=std::max(left.size(),right.size())+1;left.resize(size);right.resize(size);if(a.sign_<0)complement(left);if(b.sign_<0)complement(right);for(std::size_t i=0;i<size;++i){if constexpr(Op==0)left[i]&=right[i];else if constexpr(Op==1)left[i]|=right[i];else left[i]^=right[i];}bool negative=left.back()>>31;if(negative)complement(left);auto out=fromBinary(left);if(negative)out.sign_=-out.sign_;return out;}
 // 10^9進の筆算乗算。O(nm)。
 static BigInt mulSchoolbook(const BigInt& a,const BigInt& b){BigInt out;out.sign_=a.sign_*b.sign_;out.digits_.resize(a.digits_.size()+b.digits_.size());for(std::size_t i=0;i<a.digits_.size();++i){UInt carry=0;for(std::size_t j=0;j<b.digits_.size();++j){UInt digit=UInt(out.digits_[i+j])+UInt(a.digits_[i])*b.digits_[j]+carry;out.digits_[i+j]=digit%Base;carry=digit/Base;}out.digits_[i+b.digits_.size()]=carry;}out.normalize();return out;}
 static std::vector<std::uint32_t> convolutionDigits(const std::vector<std::uint32_t>& a,const std::vector<std::uint32_t>& b,std::uint32_t p,std::uint32_t root){auto length=a.size()+b.size()-1,size=std::bit_ceil(length);std::vector<std::uint32_t> out(size);detail::avx2_ntt::convolution_ntt_friendly(out.data(),a.data(),a.size(),b.data(),b.size(),size,p,root,false);out.resize(length);return out;}
 template<int D> static std::vector<std::uint32_t> splitNttDigits(const BigInt& x){constexpr UInt base=D==6?1000000:100000;std::vector<std::uint32_t> out((x.digits_.size()*9+D-1)/D);UInt value=0,scale=1;std::size_t position=0;for(auto digit:x.digits_){value+=UInt(digit)*scale;scale*=Base;while(scale>=base){out[position++]=value%base;value/=base;scale/=base;}}if(scale>1)out[position]=value;return out;}
 template<int D> static BigInt restoreNttProduct(const std::vector<std::uint32_t>& c1,const std::vector<std::uint32_t>& c2,Int length,int sign){constexpr UInt base=D==6?1000000:100000;BigInt out;out.sign_=sign;out.digits_.resize(length);UInt carry=0,value=0,scale=1;Int position=0;auto append=[&](){value+=(carry%base)*scale;carry/=base;scale*=base;if(scale>=Base){out.digits_[position++]=value%Base;value/=Base;scale/=Base;}};for(std::size_t i=0;i<c1.size();++i){UInt r1=c1[i],t2=((UInt(c2[i])+2*Mod2-r1)*InvMod1)%Mod2;carry+=r1+Mod1*t2;append();}while(carry)append();if(value)out.digits_[position]=value;out.normalize();return out;}
 template<int D> static BigInt mulNtt(const BigInt& a,const BigInt& b){auto left=splitNttDigits<D>(a),right=splitNttDigits<D>(b);auto c1=convolutionDigits(left,right,Mod1,11),c2=convolutionDigits(left,right,Mod2,3);return restoreNttProduct<D>(c1,c2,a.digits_.size()+b.digits_.size(),a.sign_*b.sign_);}
 static BigInt mulAbsSmall(const BigInt& x,std::uint32_t y){BigInt out;out.sign_=1;out.digits_.resize(x.digits_.size()+1);UInt carry=0;for(std::size_t i=0;i<x.digits_.size();++i){UInt digit=UInt(x.digits_[i])*y+carry;out.digits_[i]=digit%Base;carry=digit/Base;}out.digits_.back()=carry;out.normalize();return out;}
 static std::pair<BigInt,std::uint32_t> divAbsSmall(const BigInt& x,std::uint32_t y){BigInt out;out.sign_=1;out.digits_.resize(x.digits_.size());UInt rem=0;for(Int i=Int(x.digits_.size())-1;i>=0;--i){UInt digit=rem*Base+x.digits_[i];out.digits_[i]=digit/y;rem=digit%y;}out.normalize();return {std::move(out),std::uint32_t(rem)};}
 static BigIntDivision divmodSchoolbook(const BigInt&,const BigInt&);
 struct FixedMultiplier {
  std::unique_ptr<detail::avx2_ntt::FixedConvolution> first,second;Int length=0,fixedLength=0;std::vector<std::uint32_t> c1,c2;
  FixedMultiplier()=default;
  FixedMultiplier(const BigInt& y,Int maxLeftLength){fixedLength=(Int(y.digits_.size())*3+1)/2;Int leftLength=(maxLeftLength*3+1)/2;if(std::min(fixedLength,leftLength)>LargeBaseMaxDigits||fixedLength+leftLength-1>NttMaxLength)return;length=std::bit_ceil(UInt(fixedLength+leftLength-1));auto digits=splitNttDigits<6>(y);first=std::make_unique<detail::avx2_ntt::FixedConvolution>(digits.data(),digits.size(),length,Mod1,11);second=std::make_unique<detail::avx2_ntt::FixedConvolution>(digits.data(),digits.size(),length,Mod2,3);c1.resize(length);c2.resize(length);}
  BigInt multiply(const BigInt& x,const BigInt& y){if(!first||Int(x.digits_.size())<=NttThreshold)return x*y;auto left=splitNttDigits<6>(x);c1.resize(length);c2.resize(length);first->run(c1.data(),left.data(),left.size());second->run(c2.data(),left.data(),left.size());c1.resize(left.size()+fixedLength-1);c2.resize(c1.size());return restoreNttProduct<6>(c1,c2,x.digits_.size()+y.digits_.size(),x.sign_*y.sign_);}
 };
 static BigInt shiftLeft(const BigInt& x,Int count){if(x.isZero())return {};BigInt out;out.sign_=x.sign_;out.digits_.resize(x.digits_.size()+count);std::copy(x.digits_.begin(),x.digits_.end(),out.digits_.begin()+count);return out;}
 static BigInt shiftRight(const BigInt& x,Int count){if(Int(x.digits_.size())<=count)return {};BigInt out;out.sign_=x.sign_;out.digits_.assign(x.digits_.begin()+count,x.digits_.end());return out;}
 static BigInt basePower(Int n){BigInt out;out.sign_=1;out.digits_.resize(n+1);out.digits_[n]=1;return out;}
 static BigInt reciprocalAbs(const BigInt&);
 static BigInt quotientFromReciprocal(const BigInt& x,const BigInt& inverse,Int divisorLen,Int precision){Int cut=std::max(Int(0),divisorLen-1);return shiftRight(shiftRight(x,cut)*inverse,divisorLen+precision-cut);}
 static BigIntDivision correctDivisionProduct(const BigInt&,const BigInt&,BigInt,const BigInt&);
 static BigIntDivision divmodBlocks(const BigInt&,const BigInt&);
 static BigIntDivision divmodNewton(const BigInt&,const BigInt&);
public:
 BigInt()=default;
 template<std::integral T> BigInt(T x){UInt magnitude;if constexpr(std::is_signed_v<T>){if(x<0){sign_=-1;magnitude=UInt(-(x+1))+1;}else magnitude=UInt(x);}else magnitude=UInt(x);if(magnitude&&!sign_)sign_=1;while(magnitude){digits_.push_back(magnitude%Base);magnitude/=Base;}}
 explicit BigInt(std::string_view s){if(s.empty())throw std::invalid_argument("多倍長整数の文字列が空です");Int first=0;sign_=1;if(s[0]=='+'||s[0]=='-'){if(s[0]=='-')sign_=-1;first=1;}if(first==Int(s.size()))throw std::invalid_argument("多倍長整数の数字がありません");digits_.resize((s.size()-first+8)/9);Int last=s.size(),index=0;while(last>first){Int start=std::max(first,last-9);std::uint32_t digit=0;for(Int i=start;i<last;++i){if(s[i]<'0'||s[i]>'9')throw std::invalid_argument("多倍長整数に不正な文字が含まれています");digit=digit*10+(s[i]-'0');}digits_[index++]=digit;last=start;}normalize();}
 bool isZero()const{return !sign_;}int sgn()const{return sign_;}BigInt abs()const{auto out=*this;if(out.sign_<0)out.sign_=1;return out;}BigInt operator-()const{auto out=*this;out.sign_=-out.sign_;return out;}BigInt operator+()const{return *this;}
 std::string str()const{if(!sign_)return "0";if(digits_.size()<=2){UInt value=digits_[0];if(digits_.size()==2)value+=UInt(digits_[1])*Base;return sign_<0?std::to_string(-Int(value)):std::to_string(value);}constexpr std::string_view pairs="00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899";auto top=std::to_string(digits_.back());Int signLen=sign_<0;std::string out((digits_.size()-1)*9+top.size()+signLen,'\0');if(signLen)out[0]='-';std::copy(top.begin(),top.end(),out.begin()+signLen);Int pos=out.size();for(std::size_t i=0;i+1<digits_.size();++i){auto digit=digits_[i];for(int j=0;j<4;++j){Int pair=(digit%100)*2;out[pos-1]=pairs[pair+1];out[pos-2]=pairs[pair];pos-=2;digit/=100;}out[--pos]=char('0'+digit);}return out;}
 friend int cmp(const BigInt& a,const BigInt& b){return a.sign_!=b.sign_?(a.sign_<b.sign_?-1:1):a.sign_*cmpAbs(a,b);}
 friend bool operator==(const BigInt& a,const BigInt& b){return a.sign_==b.sign_&&a.digits_==b.digits_;}friend std::strong_ordering operator<=>(const BigInt& a,const BigInt& b){return cmp(a,b)<=>0;}
 friend BigInt operator+(const BigInt& a,const BigInt& b){if(!a.sign_)return b;if(!b.sign_)return a;BigInt out;if(a.sign_==b.sign_){out=addAbs(a,b);out.sign_=a.sign_;}else if(cmpAbs(a,b)>=0){out=subAbs(a,b);out.sign_*=a.sign_;}else{out=subAbs(b,a);out.sign_*=b.sign_;}return out;}
 friend BigInt operator-(const BigInt& a,const BigInt& b){return a+(-b);}
 // NTTの係数上限に応じ10^6進/10^5進を選び、範囲外は筆算に戻る。
 friend BigInt operator*(const BigInt& a,const BigInt& b){if(!a.sign_||!b.sign_)return {};Int smaller=std::min(a.digits_.size(),b.digits_.size()),total=a.digits_.size()+b.digits_.size();if(smaller>NttThreshold){if(smaller<=(LargeBaseMaxDigits*2)/3&&total<=(NttMaxLength*2)/3)return mulNtt<6>(a,b);if(total<=(NttMaxLength*5)/9)return mulNtt<5>(a,b);}return mulSchoolbook(a,b);}
 friend BigInt operator&(const BigInt& a,const BigInt& b){return bitwise<0>(a,b);}friend BigInt operator|(const BigInt& a,const BigInt& b){return bitwise<1>(a,b);}friend BigInt operator^(const BigInt& a,const BigInt& b){return bitwise<2>(a,b);}BigInt operator~()const{return -*this-BigInt(1);}
 BigInt operator<<(Int shift)const{if(shift<0)throw std::invalid_argument("シフト量は非負整数で指定してください");if(!shift||!sign_)return *this;auto digits=binaryDigits();Int words=shift/32,bits=shift%32;std::vector<std::uint32_t> out(digits.size()+words+1);UInt carry=0;for(std::size_t i=0;i<digits.size();++i){UInt value=(UInt(digits[i])<<bits)|carry;out[i+words]=std::uint32_t(value);carry=value>>32;}out[digits.size()+words]=carry;auto result=fromBinary(out);result.sign_*=sign_;return result;}
 BigInt operator>>(Int shift)const{if(shift<0)throw std::invalid_argument("シフト量は非負整数で指定してください");if(!shift||!sign_)return *this;auto digits=binaryDigits();Int words=shift/32,bits=shift%32;if(words>=Int(digits.size()))return BigInt(sign_<0?-1:0);bool discarded=false;for(Int i=0;i<words;++i)discarded|=digits[i]!=0;discarded|=(UInt(digits[words])&((UInt(1)<<bits)-1))!=0;std::vector<std::uint32_t> out(digits.size()-words);for(std::size_t i=0;i<out.size();++i){UInt value=UInt(digits[i+words])>>bits;if(bits&&i+words+1<digits.size())value|=UInt(digits[i+words+1])<<(32-bits);out[i]=std::uint32_t(value);}auto result=fromBinary(out);if(sign_<0){if(discarded)result=result+BigInt(1);result.sign_=-result.sign_;}return result;}
 static BigIntDivision divmodTrunc(const BigInt&,const BigInt&);static BigIntDivision divmod(const BigInt&,const BigInt&);
 friend BigInt operator/(const BigInt&,const BigInt&);friend BigInt operator%(const BigInt&,const BigInt&);
 BigInt& operator+=(const BigInt& b){return *this=*this+b;}BigInt& operator-=(const BigInt& b){return *this=*this-b;}BigInt& operator*=(const BigInt& b){return *this=*this*b;}BigInt& operator/=(const BigInt& b){return *this=*this/b;}BigInt& operator%=(const BigInt& b){return *this=*this%b;}BigInt& operator&=(const BigInt& b){return *this=*this&b;}BigInt& operator|=(const BigInt& b){return *this=*this|b;}BigInt& operator^=(const BigInt& b){return *this=*this^b;}BigInt& operator<<=(Int b){return *this=*this<<b;}BigInt& operator>>=(Int b){return *this=*this>>b;}
 BigInt pow(Int exponent)const{if(exponent<0)throw std::invalid_argument("多倍長整数の指数は非負整数で指定してください");BigInt out=1,base=*this;while(exponent){if(exponent&1)out*=base;exponent>>=1;if(exponent)base*=base;}return out;}
 Int toInt()const{UInt limit=UInt(std::numeric_limits<Int>::max())+(sign_<0),magnitude=0;for(Int i=Int(digits_.size())-1;i>=0;--i){UInt digit=digits_[i];if(magnitude>limit/Base||(magnitude==limit/Base&&digit>limit%Base))throw std::overflow_error("多倍長整数が int の範囲外です");magnitude=magnitude*Base+digit;}if(sign_<0){if(magnitude==UInt(std::numeric_limits<Int>::max())+1)return std::numeric_limits<Int>::min();return -Int(magnitude);}return Int(magnitude);}
 std::size_t hash()const{std::size_t out=std::hash<int>{}(sign_);for(auto d:digits_)out^=std::hash<std::uint32_t>{}(d)+0x9e3779b97f4a7c15ULL+(out<<6)+(out>>2);return out;}
 friend std::ostream& operator<<(std::ostream& os,const BigInt& x){return os<<x.str();}
};
inline BigIntDivision BigInt::divmodSchoolbook(const BigInt& x,const BigInt& y){if(!y.sign_)throw std::domain_error("多倍長整数を 0 で割ることはできません");BigIntDivision out;if(cmpAbs(x,y)<0){out.remainder=x;return out;}if(x.digits_.size()<=2){UInt numerator=x.digits_[0],denominator=y.digits_[0];if(x.digits_.size()==2)numerator+=UInt(x.digits_[1])*Base;if(y.digits_.size()==2)denominator+=UInt(y.digits_[1])*Base;out.quotient=BigInt(numerator/denominator);out.remainder=BigInt(numerator%denominator);out.quotient.sign_*=x.sign_*y.sign_;out.remainder.sign_*=x.sign_;return out;}
 if(y.digits_.size()==1){if(y.digits_[0]==1){out.quotient=x;out.quotient.sign_*=y.sign_;return out;}auto [q,r]=divAbsSmall(x,y.digits_[0]);out.quotient=std::move(q);out.quotient.sign_*=x.sign_*y.sign_;out.remainder=BigInt(r);out.remainder.sign_*=x.sign_;return out;}
 auto factor=std::uint32_t(Base/(UInt(y.digits_.back())+1));BigInt dividend=mulAbsSmall(x,factor),divisor=mulAbsSmall(y,factor);Int n=divisor.digits_.size(),qlen=Int(x.digits_.size())-n+1;dividend.digits_.resize(x.digits_.size()+1);out.quotient.sign_=x.sign_*y.sign_;out.quotient.digits_.resize(qlen);
 for(Int j=qlen-1;j>=0;--j){UInt top=UInt(dividend.digits_[j+n])*Base+dividend.digits_[j+n-1],estimate=std::min(Base-1,top/divisor.digits_[n-1]),remainder=top-estimate*divisor.digits_[n-1];while(remainder<Base&&estimate*divisor.digits_[n-2]>remainder*Base+dividend.digits_[j+n-2]){--estimate;remainder+=divisor.digits_[n-1];}Int borrow=0;for(Int i=0;i<n;++i){UInt product=estimate*divisor.digits_[i]+UInt(borrow);Int digit=Int(dividend.digits_[j+i])-Int(product%Base);borrow=product/Base;if(digit<0){digit+=Base;++borrow;}dividend.digits_[j+i]=digit;}Int last=Int(dividend.digits_[j+n])-borrow;if(last<0){--estimate;UInt carry=0;for(Int i=0;i<n;++i){UInt digit=UInt(dividend.digits_[j+i])+divisor.digits_[i]+carry;dividend.digits_[j+i]=digit%Base;carry=digit/Base;}last+=Int(carry);}dividend.digits_[j+n]=last;out.quotient.digits_[j]=estimate;}
 out.quotient.normalize();dividend.digits_.resize(n);dividend.normalize();out.remainder=divAbsSmall(dividend,factor).first;out.remainder.sign_*=x.sign_;return out;
}
// 上位半分にガード2桁を加え、B^(2m)/xの下側・誤差2未満の逆数を求める。
inline BigInt BigInt::reciprocalAbs(const BigInt& x){Int m=x.digits_.size();if(m<=32)return divmodSchoolbook(basePower(2*m),x).quotient;Int half=(m+1)/2+2,low=m-half;auto inverse=reciprocalAbs(shiftRight(x,low));auto product=x*(inverse*inverse);auto correction=shiftRight(product,2*half);for(Int i=0;i<std::min(2*half,Int(product.digits_.size()));++i)if(product.digits_[i]){correction+=1;break;}return shiftLeft(mulAbsSmall(inverse,2),low)-correction;}
inline BigIntDivision BigInt::correctDivisionProduct(const BigInt& x,const BigInt& y,BigInt quotient,const BigInt& product){BigIntDivision out{std::move(quotient),x-product};if(out.remainder.sign_<0){out.quotient-=1;out.remainder+=y;}for(int i=0;i<3;++i){if(cmpAbs(out.remainder,y)<0)break;out.quotient+=1;out.remainder-=y;}return out;}
// 長い被除数を除数長のブロックに分け、逆数と固定側NTTを再利用する。
inline BigIntDivision BigInt::divmodBlocks(const BigInt& x,const BigInt& y){Int n=x.digits_.size(),m=y.digits_.size();auto inverse=reciprocalAbs(y);FixedMultiplier inverseMultiplier,divisorMultiplier;if(n>=4*m){inverseMultiplier=FixedMultiplier(inverse,m+1);divisorMultiplier=FixedMultiplier(y,m);}BigIntDivision out;out.quotient.sign_=1;out.quotient.digits_.resize(n-m+1);for(Int block=(n-1)/m;block>=0;--block){Int offset=block*m,width=std::min(m,n-offset);BigInt dividend;dividend.sign_=1;dividend.digits_.resize(width+out.remainder.digits_.size());std::copy_n(x.digits_.begin()+offset,width,dividend.digits_.begin());std::copy(out.remainder.digits_.begin(),out.remainder.digits_.end(),dividend.digits_.begin()+width);dividend.normalize();if(cmpAbs(dividend,y)<0){out.remainder=std::move(dividend);continue;}auto quotient=shiftRight(inverseMultiplier.multiply(shiftRight(dividend,m-1),inverse),m+1);auto division=correctDivisionProduct(dividend,y,quotient,divisorMultiplier.multiply(quotient,y));std::copy(division.quotient.digits_.begin(),division.quotient.digits_.end(),out.quotient.digits_.begin()+offset);out.remainder=std::move(division.remainder);}out.quotient.normalize();return out;}
inline BigIntDivision BigInt::divmodNewton(const BigInt& x,const BigInt& y){auto dividend=x.abs(),divisor=y.abs();Int n=dividend.digits_.size(),m=divisor.digits_.size();BigIntDivision out;if(n>2*m)out=divmodBlocks(dividend,divisor);else{Int cut=std::max(Int(0),m-(n-m+2));auto high=shiftRight(divisor,cut);Int precision=std::max(m-cut,n-m);auto inverse=reciprocalAbs(shiftLeft(high,precision-(m-cut)));auto quotient=quotientFromReciprocal(shiftRight(dividend,cut),inverse,m-cut,precision);out=correctDivisionProduct(dividend,divisor,quotient,quotient*divisor);}out.quotient.sign_*=x.sign_*y.sign_;out.remainder.sign_*=x.sign_;return out;}
inline BigIntDivision BigInt::divmodTrunc(const BigInt& x,const BigInt& y){Int n=x.digits_.size(),m=y.digits_.size();if(std::min(m,n-m)>NewtonThreshold){Int size=n>2*m?2*m+8:std::max(n+1,2*std::min(m,n-m+2)+8);if(size<=(NttMaxLength*5)/9)return divmodNewton(x,y);}return divmodSchoolbook(x,y);}
inline BigIntDivision BigInt::divmod(const BigInt& x,const BigInt& y){auto out=divmodTrunc(x,y);if(!out.remainder.isZero()&&x.sign_!=y.sign_){out.quotient-=1;out.remainder+=y;}return out;}
inline BigInt operator/(const BigInt& x,const BigInt& y){return BigInt::divmodTrunc(x,y).quotient;}
// 元の%と同じ床除算の余り。0方向の余りはmod()で取得する。
inline BigInt operator%(const BigInt& x,const BigInt& y){return BigInt::divmod(x,y).remainder;}
inline BigIntDivision divmod(const BigInt& x,const BigInt& y){return BigInt::divmod(x,y);}inline BigIntDivision divmodTrunc(const BigInt& x,const BigInt& y){return BigInt::divmodTrunc(x,y);}
inline BigInt div(const BigInt& x,const BigInt& y){return x/y;}inline BigInt mod(const BigInt& x,const BigInt& y){return BigInt::divmodTrunc(x,y).remainder;}inline BigInt floor_div(const BigInt& x,const BigInt& y){return BigInt::divmod(x,y).quotient;}
inline BigInt& div_assign(BigInt& x,const BigInt& y){return x=x/y;}inline BigInt& mod_assign(BigInt& x,const BigInt& y){return x=mod(x,y);}
inline BigInt parseBigInt(std::string_view s){return BigInt(s);}template<class T> BigInt initBigInt(const T& x){return BigInt(x);}template<std::integral T> BigInt toBigInt(T x){return BigInt(x);}
inline BigInt abs(const BigInt& x){return x.abs();}inline int sgn(const BigInt& x){return x.sgn();}inline bool isZero(const BigInt& x){return x.isZero();}inline Int toInt(const BigInt& x){return x.toInt();}inline std::size_t hash(const BigInt& x){return x.hash();}inline BigInt pow(const BigInt& x,Int n){return x.pow(n);}
inline BigInt gcd(const BigInt& x,const BigInt& y){BigInt a=x.abs(),b=y.abs();while(!b.isZero()){auto r=mod(a,b);a=std::move(b);b=std::move(r);}return a;}
inline BigInt lcm(const BigInt& x,const BigInt& y){if(x.isZero()||y.isZero())return {};return ((x/gcd(x,y))*y).abs();}
inline BigInt operator""_bi(const char* s){std::string out;for(;*s;++s)if(*s!='\''&&*s!='_')out+=*s;return BigInt(out);}inline BigInt operator""_bi(const char* s,std::size_t n){std::string out;for(std::size_t i=0;i<n;++i)if(s[i]!='\''&&s[i]!='_')out+=s[i];return BigInt(out);}
}
namespace std {template<> struct hash<cplib::BigInt>{size_t operator()(const cplib::BigInt& x)const{return x.hash();}};}
